// LAYAR LAPORAN & DOKUMEN — GAMBAR & KETUKAN (putaran 19). Enam keluarga: Laba · Harian · Bulanan · Neraca · Dokumen · Setelan.
// Angka & dokumen di laporan-logika.js (tanpa DOM, dijaga uji_laporan_baru.py). Satu markup tiga lebar: HP tumpukan · Tablet dua kolom · Mac tiga kolom.
// Kertas dokumen (putih, siap cetak) satu penyusun untuk layar, dialog cetak/PDF (#cetakDokumen), dan WhatsApp (wujud teks).
import { h, mentah, pasang, delegasi } from '../inti/dom.js';
import { terkunci } from '../inti/kunci.js';
import { buatKeadaan } from '../inti/keadaan.js';
import { RP, ANGKA, tanggalPendek } from '../inti/format.js';
import * as LP from './laporan-logika.js';
import * as PJ from './pajak-logika.js';
import { waktuSekarang } from './jual-logika.js';
import { gulirkan } from '../inti/gerak.js';
import { sumberData, dengarkan, tulisDokumen } from '../data/toko.js';

const IKON = {
  gelap: '<svg viewBox="0 0 24 24" width="18" height="18" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M20 14.5A8 8 0 0 1 9.5 4a8 8 0 1 0 10.5 10.5z"/></svg>',
  terang: '<svg viewBox="0 0 24 24" width="18" height="18" fill="none" stroke="currentColor" stroke-width="1.8"><circle cx="12" cy="12" r="4"/><path d="M12 2v3M12 19v3M2 12h3M19 12h3M4.9 4.9l2.1 2.1M17 17l2.1 2.1M4.9 19.1 7 17M17 7l2.1-2.1"/></svg>',
};
const KUNCI_KELUARGA = 'miqbal_baru_laporan_keluarga';
const simpanLokal = (k, v) => { try { if (v !== null && v !== undefined) localStorage.setItem(k, String(v)); else localStorage.removeItem(k); } catch (e) { /* abaikan */ } };
const bacaLokal = (k) => { try { return localStorage.getItem(k); } catch (e) { return null; } };
const PAKET_AWAL = () => ({ labarugi: true, neraca: true, aruskas: true, omzet: true });

export function pasangLayarLaporan(akar, opsi) {
  const K = buatKeadaan({ keluarga: LP.KELUARGA_LAPORAN.some((k) => k[0] === bacaLokal(KUNCI_KELUARGA)) ? bacaLokal(KUNCI_KELUARGA) : 'laba', kabar: '', kabarAwas: false,
    bulanL: null, kepingL: 'kotor', bukaTT: false, bukaRugi: false, bukaSusut: false,
    hariH: null, bukaBuku: false, mingguM: null, tahunT: null,
    bulanB: null, tabB: 'ringkas', aturR: null, yakinBatal: false, pilihBukti: {},
    sampaiN: '', aturN: null,
    tabD: 'laporan', jenisD: 'labarugi', keD: null, rentangD: 1, bandingD: null, paket: PAKET_AWAL(), jenisK: 'setor', pilihK: {}, cariK: '',
    drafI: null, isiI: null, aturD: null, sibuk: false,
    drafPj: null, drafSetor: null, drafLuar: null, yakinPj: null });
  const set = (p) => K.setel(p); const st = () => K.baca();
  let tampil = false; const kini = () => opsi.sekarang() || new Date(); const waktu = () => waktuSekarang(opsi.sekarang() || undefined); const iso = () => waktu().tanggal;
  const lebar = () => (window.matchMedia('(min-width: 1100px)').matches ? 'mac' : window.matchMedia('(min-width: 720px)').matches ? 'tablet' : 'hp');
  const bulanKini = () => iso().slice(0, 7);
  const keTujuan = (t) => { if (opsi.keTujuan) opsi.keTujuan(t); else if (opsi.pindah) opsi.pindah(t.ke); };

  async function tulis(r, tanpaKabar) {
    if (r.tolak) { set({ kabar: r.tolak, kabarAwas: true }); return false; }
    try { let x = null; if (r.dokumen && r.dokumen.length) { x = await tulisDokumen(r.dokumen); if (x && x.gagal) { set({ kabar: 'DITOLAK: ' + x.pesan, kabarAwas: true }); return false; } }
      if (!tanpaKabar) set(Object.assign({}, r.patch || {}, { kabar: (x && x.simulasi ? 'SIMULASI — ' : '') + ((r.patch || {}).kabar || ''), kabarAwas: !!(r.patch || {}).kabarAwas })); else if (r.patch) { const p = Object.assign({}, r.patch); delete p.kabar; delete p.kabarAwas; set(p); }
      return true; } catch (e) { set({ kabar: 'GAGAL menyimpan: ' + (e && e.message ? e.message : e), kabarAwas: true }); return false; }
  }
  const bukaWa = (teks) => { try { return window.open('https://wa.me/?text=' + encodeURIComponent(teks), '_blank', 'noopener'); } catch (e) { return null; } };
  const cetakHtml = (html) => { const w = document.getElementById('cetakDokumen'); if (!w) return; w.innerHTML = html; document.body.classList.add('cetak-dokumen'); const lepas = () => { document.body.classList.remove('cetak-dokumen'); window.removeEventListener('afterprint', lepas); }; window.addEventListener('afterprint', lepas); try { window.print(); } catch (e) { /* abaikan */ } setTimeout(lepas, 4000); };

  // ---------- kertas dokumen: satu penyusun untuk layar & dialog cetak ----------
  const kopHtml = (k) => h`<div class="dk-kop ${k.gaya === 'tengah' ? 'tengah' : ''}"><div><div class="nm">${k.nama}</div>${k.alamat ? h`<div class="al">${k.alamat}</div>` : ''}${k.resmi ? h`<div class="al">${k.resmi}</div>` : ''}</div></div>`;
  const kertas = (D, nomor, kunci, ekstra) => h`<div class="dk-kertas" data-k="${kunci || 'kertas'}">${D.cap ? h`<div class="dk-cap">${D.cap}</div>` : ''}${kopHtml(D.kop)}<div class="dk-judul">${D.judul}</div><div class="dk-sub">${D.sub}</div>
    <table class="dk-tabel">${(D.baris || []).map((r, i) => h`<tr class="${r.kelas || ''}" data-k="r-${i}"><td>${r.nama}</td><td class="n">${r.teks || ''}</td>${D.adaSaldo ? h`<td class="n s2">${r.teksSaldo || ''}</td>` : ''}</tr>`)}</table>
    ${ekstra || ''}${D.identitas || D.catatan ? h`<div class="dk-sub kiri">${D.identitas || D.catatan}</div>` : ''}
    <div class="dk-kaki"><span>${D.kop.slogan || ''}</span><span>${nomor ? 'No. ' + ANGKA(nomor) + ' · ' : ''}kop v${D.kop.versi} · ${tanggalPendek(iso())}</span></div></div>`;
  /** Keluarkan satu dokumen: catat nomornya, lalu cetak / PDF (dialog cetak) / WA (teks). */
  async function keluarkan(D, info, cara) {
    if (D.tolak) { set({ kabar: D.tolak, kabarAwas: true }); return; } const r = LP.susunCetakan(info, cara, waktu()); if (!(await tulis(r))) return;
    if (cara === 'wa') { const w = bukaWa(D.teksTambahan ? (D.cap ? D.cap + '\n' : '') + D.teksTambahan + '\nNo. ' + ANGKA(r.nomor) : LP.teksDokumen(D, r.nomor, iso())); if (!w) set({ kabar: 'Peramban menahan jendela WhatsApp — ketuk lagi', kabarAwas: true }); }
    else cetakHtml(kertas(D, r.nomor).html);
  }
  const tigaTombol = (aksi, tolak, ekstra) => h`<div class="lp-tiga" data-k="aksi-${aksi}"><div class="utama ${tolak ? 'redup' : ''}" data-aksi="${aksi}" data-cara="cetak">CETAK</div><div class="kaca-btn aktif" data-aksi="${aksi}" data-cara="pdf">simpan PDF</div><div class="kaca-btn" data-aksi="${aksi}" data-cara="wa">kirim WA</div>${ekstra || ''}</div>${tolak ? h`<div class="pita-info awas" data-k="tolak-${aksi}">${tolak}</div>` : ''}`;
  const riwayatHtml = () => { const R = LP.riwayatCetakan(8); return R.length ? h`<div class="kartu platina" data-k="riwayat" style="gap: 2px;"><div class="label">Cetakan bernomor · ${R.length} terakhir</div>${R.map((l) => h`<div class="lp-baris dua" data-k="rc-${l.id}"><div><div>No. ${ANGKA(l.nomor)} · ${l.teks}</div><div class="k2">${tanggalPendek(l.tanggal)} ${l.jam}</div></div></div>`)}</div>` : ''; };

  const AKSI = {
    keluarga: ({ nama }) => { simpanLokal(KUNCI_KELUARGA, nama); set({ keluarga: nama, kabar: '' }); }, mgMinggu: ({ a }) => set({ mingguM: a }), thTahun: ({ t }) => set({ tahunT: Number(t) }), mode: () => opsi.gantiMode(), tutupKabar: () => set({ kabar: '' }), keMenu: () => opsi.pindah && opsi.pindah('menu'),
    tujuan: ({ ke, keluarga, tab, lembar, sistem }) => keTujuan({ ke, keluarga, tab, lembar, sistem }),
    // ---- LABA
    lbBulan: ({ b }) => set({ bulanL: b, kabar: '', bukaTT: false, bukaRugi: false }), lbKeping: ({ kp }) => set({ kepingL: kp }), lbBukaTT: () => set({ bukaTT: !st().bukaTT }), lbBukaRugi: () => set({ bukaRugi: !st().bukaRugi }), lbBukaSusut: () => set({ bukaSusut: !st().bukaSusut }),
    // ---- HARIAN
    hrHari: ({ t }) => set({ hariH: t, kabar: '' }), hrBuku: () => set({ bukaBuku: !st().bukaBuku }),
    hrKeluar: async ({ cara }) => { const t = st().hariH || iso(); const R = LP.rekapHari(t); const I = LP.identitasUsaha(); const D = { kop: LP.kopUntuk(LP.pakaiKop().pakai.harian, I), judul: 'Rekap Harian', sub: tanggalPendek(t) + ' · ' + R.n + ' nota' + (R.tutup ? ' · sudah tutup hari' : ''), baris: barisRekap(R), catatan: 'Kas bersih = masuk − keluar hari itu; bon belum jadi uang.', tolak: I.lengkap ? '' : 'Kop belum lengkap: nama & alamat wajib (Setelan)' };
      if (cara === 'wa') { const w = bukaWa(LP.teksRekapHari(R, D.kop)); set({ kabar: w ? 'Rekap ' + tanggalPendek(t) + ' dibuka di WhatsApp' : 'Peramban menahan jendela WhatsApp — ketuk lagi', kabarAwas: !w }); return; } await keluarkan(D, { jenis: 'harian', judul: 'Rekap harian', periode: tanggalPendek(t) }, cara); },
    // ---- BULANAN
    blBulan: ({ b }) => set({ bulanB: b, kabar: '', yakinBatal: false }), blTab: ({ t }) => set({ tabB: t, kabar: '' }),
    blAturBuka: () => { const A = LP.aturRekap(); set({ aturR: { tarifPerMil: A.tarifPerMil ? String(A.tarifPerMil) : '', batasOmzet: A.batasOmzet ? String(A.batasOmzet) : '', tanggalLapor: String(A.tanggalLapor) } }); }, blAturTutup: () => set({ aturR: null }),
    blAturKetik: (v, el) => { const a = Object.assign({}, st().aturR); a[el.dataset.kunci] = v; set({ aturR: a }); }, blAturSimpan: () => tulis(LP.susunAturRekap(st().aturR || {}, waktu())),
    blTandai: async ({ b }) => { const r = LP.susunTandaLapor(b, waktu(), st().yakinBatal); if (r.tolak && r.perluYakin) { set({ yakinBatal: true, kabar: r.tolak, kabarAwas: false }); return; } await tulis(r); },
    blPilihBukti: ({ b }) => { const p = Object.assign({}, st().pilihBukti); p[b] = !p[b]; set({ pilihBukti: p, kabar: '' }); },
    blBuktiKeluar: async ({ cara }) => { const B = LP.buktiOmzet(st().pilihBukti, kini()); const I = LP.identitasUsaha(); const D = { kop: LP.kopUntuk(LP.pakaiKop().pakai.omzet, I), judul: 'Bukti Omzet', sub: B.judul, baris: B.baris.map((b) => ({ nama: b.nama + ' · ' + b.tanda, teks: RP(b.n) })).concat([{ nama: 'Jumlah', teks: RP(B.total), kelas: 'jumlah' }]), catatan: 'Jumlah = Σ bulan yang dipilih · dari mesin laba (satu sumber)', tolak: B.tolak || (I.lengkap ? '' : 'Kop belum lengkap: nama & alamat wajib') }; await keluarkan(D, { jenis: 'bukti', judul: 'Bukti omzet', periode: B.n + ' bulan' }, cara); },
    blRekapKeluar: async ({ cara }) => { const D = dokRekap(); await keluarkan(D, { jenis: 'omzet', judul: 'Rekap omzet 12 bulan', periode: D.periode, draf: true }, cara); },
    // ---- PAJAK (putaran 24, owner saja) — perkiraan, bukan nasihat pajak
    pjProfilBuka: () => { const P = PJ.pjProfil(); const s2 = (v) => (v === null || v === undefined || v === 0 ? '' : String(v)); set({ drafPj: { wpAtasNama: P.wpAtasNama, jenisWp: P.jenisWp, statusPkp: P.statusPkp, statusPasangan: P.statusPasangan, tahunMulaiTarifFinal: s2(P.tahunMulaiTarifFinal), omzetTahunLalu: P.omzetTahunLalu === null ? '' : String(P.omzetTahunLalu), batasBebas: P.batasBebas === null ? '' : String(P.batasBebas), batasOmzet: s2(P.batasOmzet), tarifPerMil: s2(P.tarifPerMil) } }); },
    pjProfilTutup: () => set({ drafPj: null }), pjProfilKetik: (v, el) => { const d = Object.assign({}, st().drafPj); d[el.dataset.kunci] = String(v).slice(0, 80); set({ drafPj: d }); },
    pjProfilPilih: ({ kunci, nilai }) => { const d = Object.assign({}, st().drafPj); d[kunci] = nilai; set({ drafPj: d }); }, pjProfilSimpan: () => tulis(PJ.susunProfilPajak(st().drafPj || {}, waktu())),
    pjPakaiAturan: () => tulis(PJ.susunPakaiAturan(waktu())),
    pjLuarBuka: ({ b, sumber }) => set({ drafLuar: { bulan: b || bulanKini(), sumber: sumber || 'catatanLama', jumlah: (() => { const n = PJ.pjOmzetLuar(b || bulanKini(), sumber || 'catatanLama'); return n === null ? '' : String(n); })(), keterangan: '' }, yakinPj: null }),
    pjLuarTutup: () => set({ drafLuar: null }), pjLuarKetik: (v, el) => { const d = Object.assign({}, st().drafLuar); d[el.dataset.kunci] = String(v).slice(0, 120); set({ drafLuar: d }); },
    pjLuarPilih: ({ kunci, nilai }) => { const d = Object.assign({}, st().drafLuar); d[kunci] = nilai; set({ drafLuar: d }); }, pjLuarSimpan: () => tulis(PJ.susunOmzetLuar(st().drafLuar || {}, waktu())),
    pjLuarHapus: async ({ id }) => { const r = PJ.susunHapusOmzetLuar(id, st().yakinPj === 'l:' + id); if (r.perluYakin) return set({ yakinPj: 'l:' + id, kabar: r.tolak, kabarAwas: false }); await tulis(r); },
    pjSetorBuka: ({ b }) => { const T = PJ.pjTahun(null, kini()); const bl = T.daftar.find((x) => x.key === b) || null; set({ drafSetor: { masaPajak: b || '', tanggalSetor: iso(), jumlah: bl && bl.pph > 0 ? String(Math.max(0, bl.pph - bl.jumlahSetor)) : '', ntpn: '', atasNama: PJ.pjProfil().wpAtasNama, catatan: '' }, yakinPj: null }); },
    pjSetorTutup: () => set({ drafSetor: null }), pjSetorKetik: (v, el) => { const d = Object.assign({}, st().drafSetor); d[el.dataset.kunci] = String(v).slice(0, 160); set({ drafSetor: d }); },
    pjSetorKetikMasa: ({ b }) => { const d = Object.assign({}, st().drafSetor); d.masaPajak = b; set({ drafSetor: d }); },
    pjSetorSimpan: () => tulis(PJ.susunSetoran(st().drafSetor || {}, waktu(), kini())),
    pjSetorHapus: async ({ id }) => { const r = PJ.susunHapusSetoran(id, st().yakinPj === 's:' + id); if (r.perluYakin) return set({ yakinPj: 's:' + id, kabar: r.tolak, kabarAwas: false }); await tulis(r); },
    pjKeluar: async ({ cara }) => { const T = PJ.pjTahun(null, kini()); const D = PJ.dokRekapPajak(T, LP.kopUntuk(LP.pakaiKop().pakai.omzet, LP.identitasUsaha())); const I = LP.identitasUsaha(); if (!I.lengkap) D.tolak = 'Kop belum lengkap: nama & alamat wajib (Setelan → Kop & identitas)'; await keluarkan(D, { jenis: 'pajak', judul: 'Rekap pajak untuk konsultan', periode: String(T.tahun), draf: !T.lengkap }, cara); },
    // ---- NERACA
    nrSampai: (v) => set({ sampaiN: /^\d{4}-\d{2}-\d{2}$/.test(v) && v <= iso() ? v : '', kabar: '' }), nrHariIni: () => set({ sampaiN: '' }),
    nrAturBuka: () => { const A = LP.aturLaporan(); set({ aturN: { asetTetap: A.asetTetap ? String(A.asetTetap) : '', asetKet: A.asetKet } }); }, nrAturTutup: () => set({ aturN: null }), nrAturKetik: (v, el) => { const a = Object.assign({}, st().aturN); a[el.dataset.kunci] = v; set({ aturN: a }); }, nrAturSimpan: () => tulis(LP.susunAturLaporan(st().aturN || {}, waktu())),
    nrKeluar: async ({ cara }) => { const D = LP.laporanBerkop('neraca', (st().sampaiN || iso()).slice(0, 7), 1, kini()); if (st().sampaiN) { const NP = LP.neracaPada(st().sampaiN, kini()); D.sub = 'per ' + tanggalPendek(st().sampaiN) + ' · ' + (D.final ? 'FINAL' : 'DRAF — belum tutup buku'); D.baris = barisNeraca(NP); D.catatan = NP.catatan; D.tolak = NP.tolak || D.tolak; } await keluarkan(D, { jenis: 'neraca', judul: 'Neraca', periode: D.sub.split(' · ')[0], draf: !D.final }, cara); },
    // ---- DOKUMEN
    dkTab: ({ t }) => set({ tabD: t, kabar: '' }), dkJenis: ({ j }) => set({ jenisD: j, kabar: '' }), dkKe: ({ b }) => set({ keD: b, kabar: '' }), dkRentang: ({ n }) => set({ rentangD: Number(n) }), dkBanding: ({ b }) => set({ bandingD: b }),
    dkKeluar: async ({ cara }) => { const s = st(); const D = LP.laporanBerkop(s.jenisD, s.keD || bulanKini(), s.rentangD, kini()); await keluarkan(D, { jenis: D.jenis, judul: D.judul, periode: D.periode, draf: !D.final }, cara); },
    dkPaket: ({ id }) => { const p = Object.assign({}, st().paket); p[id] = !p[id]; set({ paket: p, kabar: '' }); },
    dkPaketSusun: async () => { const P = LP.paketBank(st().paket, kini()); if (P.tolak) { set({ kabar: P.tolak, kabarAwas: true }); return; } const halaman = []; let nomor = null;
      for (const D of P.daftar) { const dok = D.jenis === 'omzet' ? dokRekap() : D; const r = LP.susunCetakan({ jenis: dok.jenis || 'omzet', judul: dok.judul, periode: dok.periode, draf: false, paket: true }, 'pdf', waktu()); if (!(await tulis(r, true))) return; if (nomor === null) nomor = r.nomor; halaman.push(kertas(dok, r.nomor, 'p' + r.nomor).html); }
      cetakHtml(halaman.join('<div class="dk-pisah"></div>')); set({ kabar: 'Paket bank ' + P.daftar.length + ' dokumen (No. ' + ANGKA(nomor) + '–' + ANGKA(nomor + P.daftar.length - 1) + ') dibuka di dialog cetak — pilih "Simpan sebagai PDF", semua dari bulan FINAL', kabarAwas: false }); },
    dkKecilJenis: ({ j }) => set({ jenisK: j, kabar: '' }), dkKecilPilih: ({ id }) => { const p = Object.assign({}, st().pilihK); p[st().jenisK] = id; set({ pilihK: p, kabar: '' }); }, dkKecilCari: (v) => { const p = Object.assign({}, st().pilihK); delete p.nota; set({ cariK: String(v).slice(0, 40), pilihK: p }); },
    dkKecilKeluar: async ({ cara }) => { const s = st(); const D = LP.dokumenKecil(s.jenisK, s.pilihK[s.jenisK] || null, s.cariK, kini()); await keluarkan(D, { jenis: D.jenis, judul: D.judul, periode: D.sub, trxId: D.trxId, salinanKe: D.salinanKe }, cara); },
    // ---- SETELAN (DK1)
    stIsi: ({ kol }) => { const I = LP.identitasUsaha(); const d = st().drafI || Object.assign({}, I); set({ drafI: d, isiI: kol, kabar: '' }); }, stKetik: (v) => { const s = st(); if (!s.isiI) return; const d = Object.assign({}, s.drafI || LP.identitasUsaha()); d[s.isiI] = String(v).slice(0, 120); set({ drafI: d }); },
    stGaya: ({ g }) => { const d = Object.assign({}, st().drafI || LP.identitasUsaha()); d.gaya = g; set({ drafI: d }); },
    stNpwpKop: ({ v }) => { const d = Object.assign({}, st().drafI || LP.identitasUsaha()); d.npwpDiKop = v === 'ya'; set({ drafI: d }); }, stKosongkan: () => { const s = st(); const k = LP.KOLOM_IDENTITAS.find((x) => x.id === s.isiI); if (!k) return; if (k.ket === 'wajib') { set({ kabar: k.nama + ' wajib — tidak bisa dikosongkan', kabarAwas: true }); return; } const d = Object.assign({}, s.drafI || LP.identitasUsaha()); d[k.id] = ''; set({ drafI: d, kabar: k.nama + ' dikosongkan — baris ini tidak dicetak di kop', kabarAwas: false }); },
    stBatal: () => set({ drafI: null, isiI: null, kabar: 'Perubahan dibuang', kabarAwas: false }), stSimpan: () => tulis(LP.susunIdentitas(st().drafI || {}, waktu())),
    stPutar: async ({ d }) => { const P = LP.pakaiKop(); const pakai = {}; pakai[d] = P.pakai[d] === 'penuh' ? 'ringkas' : 'penuh'; const r = LP.susunAturDokumen({ pakai }, waktu()); if (r.patch) r.patch.kabar = (LP.DOKUMEN_KOP.find((x) => x.id === d) || {}).nama + ' kini memakai ' + (pakai[d] === 'penuh' ? 'kop penuh (dengan NPWP/NIB)' : 'kop ringkas (tanpa NPWP/NIB)'); await tulis(r); },
    stAturBuka: () => set({ aturD: { nomorAwal: String(LP.pakaiKop().nomorAwal) } }), stAturTutup: () => set({ aturD: null }), stAturKetik: (v) => set({ aturD: { nomorAwal: v } }), stAturSimpan: () => tulis(LP.susunAturDokumen(st().aturD || {}, waktu())),
  };
  delegasi(akar, AKSI);

  // ---------- pembantu gambar ----------
  const barisRekap = (R) => [{ nama: 'Omzet', teks: RP(R.omzet) }, { nama: '  Tunai', teks: RP(R.tunai) }, { nama: '  QRIS', teks: RP(R.qris) }, { nama: '  Bon — belum jadi uang', teks: RP(R.kredit) }, { nama: 'Pembayaran bon pelanggan', teks: RP(R.pelunasan) }, { nama: 'Refund & tukar retur', teks: RP(R.refund) }, { nama: 'Belanja & biaya toko', teks: RP(R.keluarHarian) }, { nama: 'Belanja beras tunai + bongkar', teks: RP(R.belanja) }, { nama: 'Bayar bon pemasok', teks: RP(R.bayarBon) }, { nama: 'Tagihan bulanan', teks: RP(R.biayaBulanan) }, { nama: 'Ambil pribadi owner', teks: RP(R.prive) }, { nama: 'Setoran ke owner', teks: RP(R.setoran) }, { nama: 'Kas bersih hari ini', teks: RP(R.bersih), kelas: 'jumlah' }, { nama: 'Margin kotor', teks: RP(R.margin) }].filter((b) => b.kelas || b.teks !== 'Rp0' || /Omzet|Tunai|QRIS/.test(b.nama));
  const barisNeraca = (NP) => [{ nama: 'Harta', kelas: 'kel' }].concat(NP.harta.map((r) => ({ nama: r.nama, teks: r.n === null ? '—' : RP(r.n) }))).concat([{ nama: 'Jumlah harta', teks: NP.aset === null ? '—' : RP(NP.aset), kelas: 'jumlah' }, { nama: 'Kewajiban & modal', kelas: 'kel' }]).concat(NP.pasiva.map((r) => ({ nama: r.nama, teks: r.n === null ? '—' : RP(r.n) }))).concat([{ nama: 'Jumlah kewajiban & modal', teks: NP.aset === null ? '—' : RP(NP.kewajiban + NP.modal + NP.labaDitahan), kelas: 'jumlah' }]);
  const dokRekap = () => { const R = LP.rekapOmzet(kini()); const I = LP.identitasUsaha(); return { jenis: 'omzet', kop: LP.kopUntuk(LP.pakaiKop().pakai.omzet, I), judul: 'Rekap Omzet Bulanan', sub: R.daftar[0].pendek + ' – ' + LP.lpBulanPendek(R.daftar[11].key, true) + ' · dari mesin laba (satu sumber)', periode: '12 bulan', adaSaldo: true,
    baris: R.daftar.map((b) => ({ nama: b.pendek + (b.absen ? ' · sebelum ada catatan' : b.lapor ? ' ✓ dilaporkan ' + tanggalPendek(b.lapor.tgl) : b.final ? ' · final' : b.berjalan ? ' · berjalan' : ' · belum tutup buku') + (R.adaTarif && !b.absen ? ' · perkiraan ' + RP(b.perkiraan) : ''), teks: b.absen ? '—' : RP(b.omzet), teksSaldo: b.kum === null || b.absen ? '—' : RP(b.kum) })).concat([{ nama: 'Tahun ' + R.tahunIni, teks: RP(R.totalTahun), kelas: 'jumlah', teksSaldo: '' }]), catatan: R.totalTeks + '. ' + R.tarifTeks + '. Kolom kanan = kumulatif tahun berjalan.', tolak: I.lengkap ? '' : 'Kop belum lengkap: nama & alamat wajib' }; };
  const bulanCip = (aksi, aktif, daftar) => h`<div class="lp-bulan" data-k="bulan-${aksi}">${daftar.map((b) => h`<div class="seg ${b.key === aktif ? 'aktif' : ''}" data-aksi="${aksi}" data-b="${b.key}" data-k="b-${b.key}">${b.pendek}${b.final ? '' : ' ✎'}</div>`)}</div>`;
  // kolom kosong (mis. belum ada cetakan) tidak diberi tempat: Mac turun ke dua kolom, tablet ke satu — kertas tidak terjepit oleh kolom hampa
  const grid = (L, semua) => { const kolom = semua.filter((k) => k && (k.__mentah ? k.html.trim() : String(k).trim())); return L === 'hp' || kolom.length < 2 ? h`<div class="lp-grid">${kolom.map((k) => h`<div class="lp-kolom">${k}</div>`)}</div>` : L === 'tablet' ? h`<div class="lp-grid tablet">${kolom.slice(0, 2).map((k, i) => h`<div class="lp-kolom">${k}${i === 1 ? kolom.slice(2) : ''}</div>`)}</div>` : h`<div class="lp-grid mac ${kolom.length === 2 ? 'dua' : ''}">${kolom.map((k) => h`<div class="lp-kolom">${k}</div>`)}</div>`; };

  function gambar() {
    if (!tampil || terkunci()) return; const s = st(); const sumber = sumberData(); const L = lebar();
    pasang(akar, h`
      <div class="latar-bola"><div class="bola emas"></div><div class="bola platina"></div><div class="bola sampanye"></div></div>
      <header class="kepala-jual">
        <div><div class="serif" style="font-size: 26px;">Laporan</div><div class="ket">${tanggalPendek(iso())} · ${sumber.jenis === 'firestore' ? opsi.statusRingkas() : sumber.jenis === 'cadangan' ? 'membaca cadangan' : 'belum tersambung'}</div></div>
        <div style="display: flex; gap: 8px; align-items: center;"><div class="pil pil-akun ${sumber.jenis === 'firestore' ? '' : 'kedip'}" data-pil-akun title="Akun yang masuk · ketuk untuk Keluar">${sumber.jenis === 'firestore' ? opsi.statusRingkas() : sumber.jenis === 'cadangan' ? 'CADANGAN' : 'belum ada data'}</div>
          <div class="kaca-btn kecil" data-aksi="keMenu">‹ Menu</div><div class="tombol-mode" data-aksi="mode">${mentah(IKON[opsi.mode() === 'gelap' ? 'terang' : 'gelap'])}</div></div>
      </header>
      <div class="jalur rapat" data-k="keluarga">${LP.KELUARGA_LAPORAN.map(([id, nm]) => h`<div class="seg ${s.keluarga === id ? 'aktif' : ''}" data-aksi="keluarga" data-nama="${id}" data-k="kg-${id}">${nm}</div>`)}</div>
      ${s.kabar ? h`<div class="pita-info ${s.kabarAwas ? 'awas' : 'emas'}" data-k="kabar" data-aksi="tutupKabar" style="cursor: pointer;">${s.kabar}</div>` : ''}
      ${s.keluarga === 'laba' ? gambarLaba(s, L) : s.keluarga === 'harian' ? gambarHarian(s, L) : s.keluarga === 'mingguan' ? gambarMingguan(s, L) : s.keluarga === 'bulanan' ? gambarBulanan(s, L) : s.keluarga === 'pajak' ? gambarPajak(s, L) : s.keluarga === 'tahunan' ? gambarTahunan(s, L) : s.keluarga === 'neraca' ? gambarNeraca(s, L) : s.keluarga === 'dokumen' ? gambarDokumen(s, L) : gambarSetelan(s, L)}
    `);
    gulirkan(akar, RP);
  }

  // ---------- LABA · tiga keping
  function gambarLaba(s, L) {
    const daftar = LP.daftarBulan(kini(), 24); const key = s.bulanL && daftar.some((b) => b.key === s.bulanL) ? s.bulanL : bulanKini(); const B = LP.labaBulan(key, kini()); const Lb = B.L; const arah = (n) => (n < 0 ? 'rugi' : '');
    const keping = h`<div class="kartu" data-k="keping" style="gap: 8px;"><div class="label">${B.nama} · tiga angka yang tidak boleh tertukar${B.final ? '' : ' · belum tutup buku'}</div>
      <div class="lp-keping">${[['kotor', 'Margin kotor', B.margin, B.pct(B.margin, Lb.omzetHitung) + ' dari omzet ber-HPP'], ['bersih', 'Laba bersih', B.labaBersih, 'sudah − biaya, hapus buku & susut'], ['tunai', 'Diterima tunai', B.tunai, 'laba yang sudah jadi uang']].map(([id, nm, n, ket]) => h`<div class="lp-petak ${s.kepingL === id ? 'aktif' : ''} ${arah(n)}" data-aksi="lbKeping" data-kp="${id}" data-k="kp-${id}"><span class="l">${nm}</span><b data-gulir="${n}">${RP(n)}</b><i>${ket}</i></div>`)}</div>
      ${B.tanpaCatatan ? h`<div class="pita-info awas">Tidak ada satu pun catatan bertanggal ${B.nama} — sistem tidak tahu apa-apa tentang bulan itu; itu beda dari bulan yang untungnya nol.</div>` : ''}</div>`;
    let panel;
    if (s.kepingL === 'kotor') panel = h`<div class="kartu" data-k="panel-kotor" style="gap: 6px;"><div class="label">Syarat margin kotor</div><div class="lp-besar ${arah(B.margin)}">${RP(B.margin)}</div>
      ${B.cakupan === null ? h`<div class="lp-pita kosong"></div><div class="k2">belum ada nota bulan ini — cakupan belum bisa dihitung</div>` : h`<div class="lp-pita"><span style="width: ${Math.max(0, Math.min(100, B.cakupan * 100)).toFixed(1)}%;"></span></div><div class="k2">terhitung ${B.pct(B.omzetKotor, B.penyebut)} dari omzet · ${Lb.jumlahTanpaHpp ? Lb.jumlahTanpaHpp + ' nota tanpa modal (' + RP(B.omzetTanpaHpp) + ') tidak ikut' : 'semua nota ber-HPP'}</div>`}
      ${Lb.returJumlah ? h`<div class="k2">${Lb.returJumlah} retur: margin turun ${RP(Lb.returUang)} karena uang kembali${Lb.returHpp > 0 ? ', lalu naik ' + RP(Lb.returHpp) + ' karena modal barang yang kembali ke stok dibatalkan' : ''}.</div>` : ''}</div>`;
    else if (s.kepingL === 'bersih') panel = h`<div class="kartu" data-k="panel-bersih" style="gap: 2px;"><div class="label">Dari kotor turun ke bersih</div>${B.terjun.map((r, i) => h`<div class="lp-terjun ${r.kelas}" data-k="tj-${i}"><span>${r.nama}</span><b class="${arah(r.n)}">${RP(r.n)}</b></div>`)}<div class="k2" style="margin-top: 4px;">margin − biaya toko − potongan QRIS − hapus buku ± susut · ${B.nama}</div></div>`;
    else panel = h`<div class="kartu" data-k="panel-tunai" style="gap: 6px;"><div class="label">Syarat diterima tunai</div><div class="lp-besar ${arah(B.tunai)}">${RP(B.tunai)}</div><div class="k2">Laba bersih ${RP(B.labaBersih)} − margin nota bon ${RP(B.marginKredit)} (${B.nKredit} nota bon, pokok ${RP(B.omzetKredit)}). Margin bon baru jadi uang saat bonnya dibayar — lihat Pelanggan → Bon.</div></div>`;
    const aman = B.aman ? h`<div class="kartu platina" data-k="aman" style="gap: 4px;"><div class="label">Aman diambil bulan ini</div><div class="lp-terjun"><span>Batas aman (${B.aman.dariLaba ? 'laba bersih bulan berjalan' : 'setelan owner'})</span><b>${RP(B.aman.batas)}</b></div><div class="lp-terjun"><span>Sudah diambil pribadi</span><b>−${RP(B.aman.terpakai).replace('−', '')}</b></div><div class="lp-terjun jumlah"><span>Sisa</span><b class="${arah(B.aman.sisa)}">${RP(B.aman.sisa)}</b></div><div class="kaca-btn kecil" data-aksi="tujuan" data-ke="uang" data-keluarga="keluar" style="align-self: flex-start;">catat di Uang keluar ›</div></div>` : '';
    const daftarKartu = (judul, sub, buka, aksi, isi, kosongTeks) => h`<div class="kartu" data-k="k-${aksi}" style="gap: 4px;"><div class="kepala-lembar" data-aksi="${aksi}" style="cursor: pointer;"><div><div class="label">${judul}</div><div class="k2">${sub}</div></div><div class="kaca-btn kecil">${buka ? 'tutup' : 'lihat'}</div></div>${buka ? (isi.length ? isi : h`<div class="k2">${kosongTeks}</div>`) : ''}</div>`;
    const susut = daftarKartu('Susut & selisih stok', (B.susut.length ? B.susut.length + ' baris · ' : '') + (B.susutTotal < 0 ? '−' : '+') + RP(Math.abs(B.susutTotal)).replace('−', '') + ' · memotong laba, tidak menyentuh kas', s.bukaSusut, 'lbBukaSusut', B.susut.slice(0, 40).map((x, i) => h`<div class="lp-baris" data-k="su-${i}"><div class="j">${tanggalPendek(x.tanggal).slice(0, 6)}</div><div><div>${x.nama}</div><div class="k2">${x.jumlah > 0 ? '+' : ''}${x.jumlah} ${x.satuan}${x.alasan ? ' · ' + x.alasan : ''}</div></div><div class="n ${arah(x.nilaiRp)}">${(x.nilaiRp < 0 ? '−' : '+') + RP(Math.abs(x.nilaiRp))}</div></div>`), 'tidak ada susut bulan ini');
    const rugi = daftarKartu('Nota yang rugi', B.rugi.length ? B.rugi.length + ' nota dijual di bawah modal' : 'tidak ada nota rugi', s.bukaRugi, 'lbBukaRugi', B.rugi.slice(0, 40).map((p) => h`<div class="lp-baris" data-k="rg-${p.id}"><div class="j">${tanggalPendek(p.tanggal).slice(0, 6)}</div><div><div>${p.nama}</div><div class="k2">omzet ${RP(p.omzet)}</div></div><div class="n rugi">${RP(p.margin)}</div></div>`), 'tidak ada');
    const tt = daftarKartu('Nota tanpa modal — tidak ikut dihitung', B.tanpaHpp.length ? B.tanpaHpp.length + ' nota · omzet ' + RP(B.omzetTanpaHpp) + ' · isi modalnya di Stok → HPP' : 'semua nota bulan ini punya modal', s.bukaTT, 'lbBukaTT', B.tanpaHpp.slice(0, 40).map((p) => h`<div class="lp-baris" data-k="tt-${p.id}"><div class="j">${tanggalPendek(p.tanggal).slice(0, 6)}</div><div><div>${p.nama}</div><div class="k2">${p.jam}</div></div><div class="n">${RP(p.omzet)}</div></div>`), 'tidak ada');
    const pilih = h`<div class="kartu" data-k="pilih-bulan" style="gap: 6px;"><div class="label">Bulan yang dilihat · ✎ = belum tutup buku</div>${bulanCip('lbBulan', key, daftar)}</div>`;
    const kaki = h`<div class="lp-kaki">Satu mesin laba dengan sistem lama (retur ikut memotong, susut sejak 1 Sep 2026, upah KOTOR). "Diterima tunai" = laba bersih − margin nota bon: angka paling turunan di layar ini, bukan hasil hitung laci.</div>`;
    if (L === 'hp') return h`<section data-k="laba">${pilih}${keping}${panel}${aman}${susut}${rugi}${tt}${kaki}</section>`;
    return h`<section data-k="laba">${grid(L, [h`${pilih}${keping}${aman}${kaki}`, h`${panel}${susut}`, h`${rugi}${tt}`])}</section>`;
  }

  // ---------- HARIAN · rekap satu hari
  function gambarHarian(s, L) {
    const hari = LP.hariTerakhir(kini(), 14); const t = s.hariH && hari.some((x) => x.iso === s.hariH) ? s.hariH : iso(); const R = LP.rekapHari(t);
    const pilih = h`<div class="kartu" data-k="pilih-hari" style="gap: 6px;"><div class="label">Hari yang dilihat · 14 hari terakhir</div><div class="lp-bulan">${hari.map((x) => h`<div class="seg ${x.iso === t ? 'aktif' : ''} ${x.n ? '' : 'sepi'}" data-aksi="hrHari" data-t="${x.iso}" data-k="h-${x.iso}">${x.hariIni ? 'hari ini' : tanggalPendek(x.iso).slice(0, 6)}${x.n ? '' : ' ·'}</div>`)}</div></div>`;
    const hero = h`<div class="kartu hero" data-k="hero" style="gap: 4px;"><div class="label">Omzet ${t === iso() ? 'hari ini' : tanggalPendek(t)} · ${R.n} nota${R.tutup ? ' · sudah tutup hari' + (R.tutup.jam ? ' ' + R.tutup.jam : '') : t < iso() ? ' · BELUM tutup hari' : ''}</div><div class="lp-besar" data-gulir="${R.omzet}">${RP(R.omzet)}</div>
      <div class="lp-tiga3">${[['Tunai', R.tunai], ['QRIS', R.qris], ['Bon', R.kredit]].map(([nm, n]) => h`<div data-k="c-${nm}"><span class="l">${nm}</span><span class="a" data-gulir="${n}">${RP(n)}</span></div>`)}</div>
      ${R.perJam.length ? h`<div class="lp-jam" data-k="jam">${R.perJam.map((j) => h`<div data-k="j-${j.jam}" title="${j.jam}:00 · ${j.n} nota"><i style="height: ${Math.max(4, Math.round(j.omzet / R.maksJam * 44))}px;"></i><span>${j.jam}</span></div>`)}</div>` : ''}</div>`;
    const rekap = h`<div class="kartu" data-k="rekap" style="gap: 2px;"><div class="label">Rekap ${tanggalPendek(t)} · teks yang sama dengan yang dikirim WA</div>${barisRekap(R).map((b, i) => h`<div class="lp-terjun ${b.kelas || ''}" data-k="rk-${i}"><span>${b.nama}</span><b>${b.teks}</b></div>`)}${R.jumlahTanpaHpp ? h`<div class="k2">${R.jumlahTanpaHpp} nota tanpa modal tidak ikut margin.</div>` : ''}
      ${tigaTombol('hrKeluar', LP.identitasUsaha().lengkap ? '' : 'Kop belum lengkap: nama & alamat wajib (Setelan) — kirim WA tetap bisa')}</div>`;
    const arus = h`<div class="kartu" data-k="arus" style="gap: 2px;"><div class="label">Uang masuk & keluar hari itu · arus kas</div>${R.masuk.map((x, i) => h`<div class="lp-terjun" data-k="am-${i}"><span>${x.label}<small> · ${x.n} ${x.satuan}</small></span><b>+${RP(x.nominal)}</b></div>`)}${R.keluar.map((x, i) => h`<div class="lp-terjun" data-k="ak-${i}"><span>${x.label}<small> · ${x.n} ${x.satuan}</small></span><b>−${RP(x.nominal)}</b></div>`)}<div class="lp-terjun jumlah"><span>Kas bersih</span><b class="${R.bersih < 0 ? 'rugi' : ''}">${RP(R.bersih)}</b></div></div>`;
    const buku = h`<div class="kartu platina" data-k="buku" style="gap: 4px;"><div class="kepala-lembar" data-aksi="hrBuku" style="cursor: pointer;"><div><div class="label">Buku kas ${tanggalPendek(t)}</div><div class="k2">${R.buku.length} gerakan uang, satu per satu</div></div><div class="kaca-btn kecil">${s.bukaBuku ? 'tutup' : 'lihat'}</div></div>
      ${s.bukaBuku ? (R.buku.length ? R.buku.map((r, i) => h`<div class="lp-baris" data-k="bk-${i}"><div class="j">${r.jam || '—'}</div><div><div>${r.label}</div><div class="k2">${r.kantong}</div></div><div class="n ${r.keluar ? 'rugi' : ''}">${r.masuk ? '+' + RP(r.masuk) : '−' + RP(r.keluar)}</div></div>`) : h`<div class="k2">tidak ada gerakan uang</div>`) : ''}</div>`;
    const kaki = h`<div class="lp-kaki">Rekap harian = mesin arus kas & laba yang sama dengan sistem lama (dataRekapHarian). Mencatat uang keluar & tutup hari ada di layar Uang.</div>`;
    if (L === 'hp') return h`<section data-k="harian">${pilih}${hero}${rekap}${arus}${buku}${kaki}</section>`;
    return h`<section data-k="harian">${grid(L, [h`${pilih}${hero}${kaki}`, h`${rekap}`, h`${arus}${buku}`])}</section>`;
  }

  // ---------- MINGGUAN · Senin–Minggu (owner 23 Sep)
  function gambarMingguan(s, L) {
    const D = LP.daftarMinggu(kini(), 8); const awal = s.mingguM && D.some((m) => m.awal === s.mingguM) ? s.mingguM : (D[0] ? D[0].awal : LP.lpSenin(iso())); const R = LP.rekapMinggu(awal, kini()); const arah = (n) => (n < 0 ? 'rugi' : '');
    const pilih = h`<div class="kartu" data-k="pilih-minggu" style="gap: 6px;"><div class="label">Minggu yang dilihat · Senin–Minggu · 8 minggu terakhir</div><div class="lp-bulan">${D.map((m) => h`<div class="seg ${m.awal === awal ? 'aktif' : ''}" data-aksi="mgMinggu" data-a="${m.awal}" data-k="m-${m.awal}">${m.berjalan ? 'minggu ini' : m.label}</div>`)}</div></div>`;
    const hero = h`<div class="kartu hero" data-k="hero" style="gap: 4px;"><div class="label">Omzet ${R.berjalan ? 'minggu ini' : 'minggu ' + R.label} · ${R.n} nota${R.berjalan ? ' · ' + R.hariJalan + ' hari jalan' : ''}</div><div class="lp-besar" data-gulir="${R.omzet}">${RP(R.omzet)}</div>
      <div class="k2">rata ${RP(R.rataHari)} per hari · ${R.bandingTeks}${R.kredit ? ' · ' + RP(R.kredit) + ' di antaranya bon' : ''}</div>
      <div class="lp-batang tujuh" data-k="batang">${R.hari.map((d) => h`<div class="${d.hariIni ? 'aktif' : ''} ${d.depan ? 'depan' : ''}" data-k="d-${d.iso}" title="${d.nama} ${d.tgl} · ${d.n} nota"><i style="height: ${d.depan ? 3 : Math.max(3, Math.round(d.omzet / R.maks * 64))}px;"></i><span>${d.nama}<br>${d.tgl}</span></div>`)}</div>
      ${R.terbaik && R.terbaik !== R.sepi ? h`<div class="k2">paling ramai ${R.terbaik.nama} ${R.terbaik.tgl} (${RP(R.terbaik.omzet)}) · paling sepi ${R.sepi.nama} ${R.sepi.tgl} (${RP(R.sepi.omzet)})</div>` : ''}${R.kosong ? h`<div class="pita-info">Tidak ada satu pun catatan minggu ini.</div>` : ''}</div>`;
    const inti = h`<div class="kartu" data-k="inti" style="gap: 2px;"><div class="label">Inti minggu ${R.label}</div>${[['Omzet', R.omzet, ''], ['HPP barang terjual', R.hpp, R.jumlahTanpaHpp ? 'di luar ' + RP(R.omzetTanpaHpp) + ' omzet tanpa modal' : ''], ['Laba kotor', R.margin, 'omzet ber-HPP − HPP-nya'], ['Biaya toko (harian + jatah bulanan)', R.biayaToko, ''], ['Susut & selisih stok', R.susut, ''], ['Laba bersih', R.labaBersih, 'mesin yang sama dengan Laba'], ['Uang masuk (arus kas)', R.masuk, ''], ['Uang keluar (arus kas)', R.keluar, ''], ['Kas bersih', R.bersih, 'masuk − keluar']].map(([nm, n, ket], i) => h`<div class="lp-terjun ${/Laba bersih|Kas bersih/.test(nm) ? 'jumlah' : ''}" data-k="im-${i}"><span>${nm}${ket ? h`<small> · ${ket}</small>` : ''}</span><b class="${arah(n)}">${RP(n)}</b></div>`)}</div>`;
    const perHari = h`<div class="kartu" data-k="per-hari" style="gap: 2px;"><div class="label">Per hari · Σ hari = omzet minggu${R.cocokJumlah ? '' : ' · TIDAK MENUTUP — periksa'}</div>${R.hari.map((d) => h`<div class="lp-baris ${d.depan ? 'depan' : ''}" data-k="ph-${d.iso}" ${d.depan ? '' : mentah('data-aksi="tujuan" data-ke="laporan" data-keluarga="harian" style="cursor: pointer;"')}><div class="j">${d.nama} ${d.tgl}</div><div><div>${d.depan ? 'belum datang' : d.n + ' nota' + (d.hariIni ? ' · hari ini' : '')}</div><div class="k2">${d.depan ? '' : 'margin kotor ' + RP(d.margin)}</div></div><div class="n">${d.depan ? '—' : RP(d.omzet)}</div></div>`)}<div class="lp-terjun jumlah"><span>Minggu ${R.label}</span><b>${RP(R.omzet)}</b></div></div>`;
    const kaki = h`<div class="lp-kaki">Minggu toko = Senin sampai Minggu. Omzet, laba, dan kas dari mesin yang sama dengan Harian & Bulanan; banding minggu sebelumnya memakai omzet penuh (termasuk nota tanpa modal).</div>`;
    if (L === 'hp') return h`<section data-k="mingguan">${pilih}${hero}${inti}${perHari}${kaki}</section>`;
    return h`<section data-k="mingguan">${grid(L, [h`${pilih}${hero}${kaki}`, h`${inti}`, h`${perHari}`])}</section>`;
  }
  // ---------- TAHUNAN · dua belas bulan (owner 23 Sep)
  function gambarTahunan(s, L) {
    const D = LP.daftarTahun(kini()); const tahun = s.tahunT && D.some((t) => t.tahun === s.tahunT) ? s.tahunT : D[0].tahun; const R = LP.rekapTahun(tahun, kini()); const arah = (n) => (n < 0 ? 'rugi' : '');
    const pilih = D.length > 1 ? h`<div class="kartu" data-k="pilih-tahun" style="gap: 6px;"><div class="label">Tahun yang dilihat</div><div class="lp-bulan">${D.map((t) => h`<div class="seg ${t.tahun === tahun ? 'aktif' : ''}" data-aksi="thTahun" data-t="${t.tahun}" data-k="t-${t.tahun}">${t.tahun}${t.final ? '' : ' ✎'}</div>`)}</div></div>` : '';
    const hero = h`<div class="kartu hero" data-k="hero" style="gap: 4px;"><div class="label">Omzet tahun ${R.tahun} · ${R.n} nota · ${R.status}</div><div class="lp-besar" data-gulir="${R.omzet}">${RP(R.omzet)}</div>
      <div class="k2">${R.bulanJalan} bulan${R.berjalan ? ' jalan' : ''} · rata ${RP(R.rataBulan)} per bulan · ${R.bandingTeks}</div>
      <div class="lp-grafik" data-k="grafik">${R.bulan.map((b) => h`<div class="${b.final ? '' : 'draf'} ${b.berjalan ? 'aktif' : ''} ${b.depan ? 'depan' : ''}" data-k="g-${b.key}" title="${b.nama} · ${b.n} nota"><i style="height: ${b.depan ? 4 : Math.max(6, Math.round(b.omzet / R.maks * 100))}px;"></i><span>${b.pendek.slice(0, 3)}</span></div>`)}</div>
      ${R.terbaik && R.terbaik !== R.sepi ? h`<div class="k2">paling ramai ${R.terbaik.nama} (${RP(R.terbaik.omzet)}) · paling sepi ${R.sepi.nama} (${RP(R.sepi.omzet)})</div>` : ''}${R.kosong ? h`<div class="pita-info">Tidak ada satu pun catatan tahun ${R.tahun}.</div>` : ''}</div>`;
    const inti = h`<div class="kartu" data-k="inti" style="gap: 2px;"><div class="label">Inti tahun ${R.tahun} · Σ dua belas bulan</div>${[['Omzet', R.omzet, ''], ['HPP barang terjual', R.hpp, ''], ['Laba kotor', R.margin, 'omzet ber-HPP − HPP-nya'], ['Biaya toko (harian + jatah bulanan)', R.biaya, ''], ['Susut & selisih stok', R.susut, ''], ['Laba bersih', R.labaBersih, 'Σ laba bersih tiap bulan']].map(([nm, n, ket], i) => h`<div class="lp-terjun ${/Laba bersih/.test(nm) ? 'jumlah' : ''}" data-k="it-${i}"><span>${nm}${ket ? h`<small> · ${ket}</small>` : ''}</span><b class="${arah(n)}">${RP(n)}</b></div>`)}</div>`;
    const perBulan = h`<div class="kartu" data-k="per-bulan" style="gap: 2px;"><div class="label">Per bulan · omzet & laba bersih · Σ bulan = tahun${R.cocokJumlah ? '' : ' · TIDAK MENUTUP — periksa'}</div>${R.bulan.map((b) => h`<div class="lp-baris ${b.depan ? 'depan' : ''}" data-k="pb-${b.key}" ${b.depan ? '' : mentah('data-aksi="tujuan" data-ke="laporan" data-keluarga="bulanan" style="cursor: pointer;"')}><div class="j">${b.pendek.slice(0, 3)}</div><div><div>${b.depan ? 'belum datang' : b.n + ' nota' + (b.berjalan ? ' · berjalan' : b.final ? ' · final' : ' · draf')}</div><div class="k2">${b.depan ? '' : 'laba bersih ' + RP(b.labaBersih)}</div></div><div class="n">${b.depan ? '—' : RP(b.omzet)}</div></div>`)}<div class="lp-terjun jumlah"><span>Tahun ${R.tahun}</span><b>${RP(R.omzet)}</b></div></div>`;
    const kaki = h`<div class="lp-kaki">Sampai tutup buku tahun itu, semua angka tahunan DRAF (✎). Laporan berkop 12 bulan untuk bank ada di Dokumen; Rekap omzet 12 bulan bergulir (bukan tahun kalender) ada di Bulanan.</div>`;
    if (L === 'hp') return h`<section data-k="tahunan">${pilih}${hero}${inti}${perBulan}${kaki}</section>`;
    return h`<section data-k="tahunan">${grid(L, [h`${pilih}${hero}${kaki}`, h`${inti}`, h`${perBulan}`])}</section>`;
  }

  // ---------- BULANAN · enam bulan + DK3
  function gambarBulanan(s, L) {
    const E = LP.enamBulan(kini()); const key = s.bulanB && E.daftar.some((b) => b.key === s.bulanB) ? s.bulanB : bulanKini(); const I = LP.intiBulan(key, kini()); const R = LP.rekapOmzet(kini()); const A = R.A; const arah = (n) => (n < 0 ? 'rugi' : '');
    const hero = h`<div class="kartu hero" data-k="hero" style="gap: 4px;"><div class="label">Omzet ${I.nama}${I.berjalan ? ' · sampai hari ini' : ''}</div><div class="lp-besar" data-gulir="${I.omzet}">${RP(I.omzet)}</div><div class="k2">${I.hariJalan} hari${I.berjalan ? ' jalan' : ''} · rata ${RP(I.rataHari)} per hari${I.kredit ? ' · ' + RP(I.kredit) + ' di antaranya bon' : ''}</div>
      <div class="lp-batang" data-k="batang">${E.daftar.map((b) => h`<div class="${b.key === key ? 'aktif' : ''} ${b.berjalan ? 'jalan' : ''}" data-aksi="blBulan" data-b="${b.key}" data-k="b-${b.key}"><i style="height: ${Math.max(3, Math.round(b.omzet / E.maks * 64))}px;"></i><span>${b.pendek}</span></div>`)}</div></div>`;
    const inti = h`<div class="kartu" data-k="inti" style="gap: 2px;"><div class="label">Inti ${I.nama}</div>${[['Omzet', I.omzet, ''], ['HPP barang terjual', I.hpp, I.jumlahTanpaHpp ? 'di luar ' + RP(I.omzetTanpaHpp) + ' omzet tanpa modal' : ''], ['Laba kotor', I.margin, 'omzet ber-HPP − HPP-nya'], ['Biaya toko (harian + jatah bulanan)', I.biayaToko, ''], ['Laba bersih', I.labaBersih, 'ada rinciannya di Laba'], ['Uang keluar (arus kas)', I.keluar, ''], ['Kas bersih', I.bersih, 'masuk − keluar']].map(([nm, n, ket], i) => h`<div class="lp-terjun ${/Laba bersih|Kas bersih/.test(nm) ? 'jumlah' : ''}" data-k="in-${i}"><span>${nm}${ket ? h`<small> · ${ket}</small>` : ''}</span><b class="${arah(n)}">${RP(n)}</b></div>`)}
      ${I.belumBayar.length ? h`<div class="pita-info awas">Tagihan ${I.nama} yang belum dibayar: ${I.belumBayar.map((x) => x.label + ' ' + RP(x.n)).join(', ')} — bayar di Uang → Uang keluar → Tagihan.</div>` : ''}</div>`;
    const tab = h`<div class="jalur rapat" data-k="tabB">${[['ringkas', 'Rekap 12 bulan'], ['tanda', 'Tanda dilaporkan'], ['bukti', 'Bukti omzet']].map(([id, nm]) => h`<div class="seg ${s.tabB === id ? 'aktif' : ''}" data-aksi="blTab" data-t="${id}" data-k="tb-${id}">${nm}</div>`)}</div>`;
    const grafik = h`<div class="kartu" data-k="grafik" style="gap: 6px;"><div class="label">Omzet 12 bulan · batang putus = belum tutup buku</div><div class="lp-grafik">${R.daftar.map((b) => h`<div class="${b.final ? '' : 'draf'} ${b.key === key ? 'aktif' : ''}" data-aksi="blBulan" data-b="${b.key}" data-k="b-${b.key}"><i style="height: ${Math.max(6, Math.round(b.omzet / R.maks * 100))}px;"></i><span>${b.pendek.slice(0, 3)}</span></div>`)}</div>
      <div class="lp-status">${[['bulan terakhir final', R.finalTerakhir ? R.finalTerakhir.nama : 'belum ada — belum pernah tutup buku', ''], [R.tempo ? R.tempo.teks : 'tempo lapor', R.tempo ? (R.tempo.sudah ? 'sudah' : R.tempo.lewat ? 'LEWAT' : R.tempo.sisaHari !== null ? R.tempo.sisaHari + ' hari lagi' : 'belum jatuh') : '—', R.tempo && R.tempo.lewat ? 'awas' : ''], ['belum dilaporkan ' + R.tahunIni, R.belumLapor.length + ' bulan', R.belumLapor.length > 1 ? 'awas' : '']].map(([t, n, k], i) => h`<div class="${k}" data-k="st-${i}">${t}<b>${n}</b></div>`)}</div></div>`;
    const dokR = dokRekap(); let isiB;
    if (s.tabB === 'ringkas') isiB = h`${kertas(dokR, null, 'kertas-rekap')}${tigaTombol('blRekapKeluar', dokR.tolak)}`;
    else if (s.tabB === 'tanda') { const b = R.daftar.find((x) => x.key === key) || R.daftar[11]; isiB = h`<div class="kartu" data-k="tanda" style="gap: 6px;"><div class="label">Tanda "sudah dilaporkan" · hanya bulan yang sudah tutup buku</div>${bulanCip('blBulan', key, R.daftar.slice().reverse())}<div class="k2">${b.nama} · omzet ${RP(b.omzet)}${R.adaTarif ? ' · perkiraan ' + RP(b.perkiraan) : ''} · ${b.lapor ? 'sudah dilaporkan ' + tanggalPendek(b.lapor.tgl) : b.final ? 'belum dilaporkan' : 'belum tutup buku — belum bisa dilaporkan'}</div>
      <div class="${!b.final ? 'utama redup' : b.lapor ? 'kaca-btn awas' : 'utama'}" data-aksi="blTandai" data-b="${b.key}" data-k="tanda-${b.key}" style="min-height: 44px;">${b.lapor ? (s.yakinBatal ? 'YAKIN BATALKAN TANDA' : 'batalkan tanda dilaporkan') : 'TANDAI SUDAH DILAPORKAN'}</div></div>`; }
    else { const BK = LP.buktiOmzet(s.pilihBukti, kini()); isiB = h`<div class="kartu" data-k="bukti" style="gap: 6px;"><div class="label">Pilih bulan untuk bukti · hanya bulan final</div><div class="lp-bulan">${R.daftar.map((b) => h`<div class="seg ${s.pilihBukti[b.key] ? 'aktif' : ''}" data-aksi="blPilihBukti" data-b="${b.key}" data-k="bk-${b.key}">${b.pendek}${b.final ? '' : ' ✎'}${s.pilihBukti[b.key] ? ' ✓' : ''}</div>`)}</div><div class="k2">${BK.judul}</div></div>
      ${kertas({ kop: LP.kopUntuk(LP.pakaiKop().pakai.omzet), judul: 'Bukti Omzet', sub: BK.judul, baris: BK.baris.map((b) => ({ nama: b.nama + ' · ' + b.tanda, teks: RP(b.n) })).concat([{ nama: 'Jumlah', teks: RP(BK.total), kelas: 'jumlah' }]), catatan: 'Jumlah = Σ bulan yang dipilih' }, null, 'kertas-bukti')}${tigaTombol('blBuktiKeluar', BK.tolak)}`; }
    const atur = s.aturR ? h`<div class="kartu lp-lembar" data-k="aturR" style="gap: 8px;"><div class="kepala-lembar"><div class="serif" style="font-size: 18px;">Atur rekap omzet</div><div class="kaca-btn" data-aksi="blAturTutup">tutup</div></div>
      ${[['tarifPerMil', 'Tarif perkiraan — per seribu dari omzet (5 = 0,5 %). 0 = kolom tidak dicetak. Setelan owner, BUKAN nasihat pajak.'], ['batasOmzet', 'Batas omzet tahunan (rupiah). 0 = belum diatur.'], ['tanggalLapor', 'Tanggal lapor tiap bulan (1–28): bulan final dianggap terlambat kalau lewat tanggal ini di bulan berikutnya.']].map(([k, ket]) => h`<div data-k="ar-${k}"><div class="label">${ket}</div><input class="ketik-nama" type="text" inputmode="numeric" value="${s.aturR[k]}" data-ketik="blAturKetik" data-kunci="${k}"></div>`)}<div class="utama" data-aksi="blAturSimpan">SIMPAN</div></div>`
      : h`<div class="kaca-btn" data-aksi="blAturBuka" data-k="aturR-buka" style="min-height: 38px; font-size: 12px;">Atur tarif perkiraan, batas omzet & tanggal lapor${A.dariOwner ? ' · ' + (A.tarifPerMil ? LP.tarifTeks(A.tarifPerMil) : 'tanpa tarif') + ' · ' + (A.batasOmzet ? RP(A.batasOmzet) : 'tanpa batas') + ' · tgl ' + A.tanggalLapor : ' · belum diatur'}</div>`;
    const kePajak = h`<div class="kaca-btn aktif" data-aksi="keluarga" data-nama="pajak" data-k="ke-pajak" style="min-height: 38px; font-size: 12px;">Rincian pajak → · status per bulan, setoran & NTPN, omzet di luar sistem</div>`;
    const kaki = h`<div class="lp-kaki">Omzet dari mesin laba (satu sumber). Tanda "dilaporkan" hanya untuk bulan yang sudah tutup buku — sampai tutup buku pertama semua bulan DRAF. Tarif & batas diatur owner; bawaan belum diatur, barisnya tidak dicetak.</div>`;
    if (L === 'hp') return h`<section data-k="bulanan">${hero}${inti}${tab}${grafik}${isiB}${kePajak}${atur}${riwayatHtml()}${kaki}</section>`;
    return h`<section data-k="bulanan">${grid(L, [h`${hero}${inti}${kePajak}${atur}${kaki}`, h`${tab}${isiB}`, h`${grafik}${riwayatHtml()}`])}</section>`;
  }

  // ---------- PAJAK (putaran 24) · empat kartu + rekap untuk konsultan — semua angka PERKIRAAN, bukan nasihat pajak
  function gambarPajak(s, L) {
    const T = PJ.pjTahun(null, kini()); const P = T.P; const A = T.ambang; const pil = (v, id, aksi, kunci) => h`<div class="seg ${v === id ? 'aktif' : ''}" data-aksi="${aksi}" data-kunci="${kunci}" data-nilai="${id}">`;
    const label = h`<div class="pj-label" data-k="pj-label">${PJ.PJ_LABEL}${T.anggapanOp ? ' · ' + PJ.PJ_ANGGAPAN_OP : ''}</div>`;
    // status pasangan: teks aturan + [BELUM TERVERIFIKASI] bila dasarnya belum dibaca langsung; anggapan = pita emas
    const pasanganTeks = (A, k) => h`<div class="pita-info ${A.anggapan || A.belumTerverifikasi ? 'emas' : ''}" data-k="${k}">${A.belumTerverifikasi ? h`<b class="awas-teks">${PJ.PJ_TANDA_BELUM}</b> ` : ''}${A.teks}${A.belumTerverifikasi ? ' (' + A.belumTerverifikasi + ')' : ''}</div>`;
    const diketik = (n, sumber) => h`<span class="pj-diketik" title="diketik owner · ${sumber}">${RP(n)}<small>diketik owner · ${sumber}</small></span>`;
    // 1 · profil
    const d = s.drafPj; const profil = d ? h`<div class="kartu lp-lembar" data-k="pj-profil-atur" style="gap: 8px;"><div class="kepala-lembar"><div class="serif" style="font-size: 18px;">Profil wajib pajak</div><div class="kaca-btn" data-aksi="pjProfilTutup">tutup</div></div>
        <div class="label">Atas nama (nama saja — tanpa NIK, NPWP, atau nomor rekening)</div><input class="ketik-nama" type="text" value="${d.wpAtasNama}" data-ketik="pjProfilKetik" data-kunci="wpAtasNama" placeholder="nama wajib pajak">
        <div class="label">Jenis wajib pajak</div><div class="jalur rapat">${PJ.PJ_JENIS_WP.map((j) => h`${pil(d.jenisWp, j.id, 'pjProfilPilih', 'jenisWp')}${j.nama}</div>`)}</div>
        <div class="label">Status PKP</div><div class="jalur rapat">${PJ.PJ_STATUS_PKP.map((j) => h`${pil(d.statusPkp, j.id, 'pjProfilPilih', 'statusPkp')}${j.nama}</div>`)}</div>
        <div class="label">Status pasangan (menentukan usaha pasangan ikut batas Rp500 juta atau tidak)</div><div class="jalur rapat" style="flex-wrap: wrap;" data-k="pj-pasangan-pilih">${PJ.PJ_STATUS_PASANGAN.map((j) => h`${pil(d.statusPasangan, j.id, 'pjProfilPilih', 'statusPasangan')}${j.nama}</div>`)}</div>
        ${pasanganTeks(PJ.pjAturanPasangan(d.statusPasangan), 'pj-pasangan-draf')}
        ${[['tahunMulaiTarifFinal', 'Tahun mulai tarif final (kosong = tidak tahu)'], ['omzetTahunLalu', 'Omzet tahun lalu, rupiah (kosong = tidak diketahui — beda dengan nol)'], ['tarifPerMil', 'Tarif per seribu dari omzet (5 = 0,5 %)'], ['batasBebas', 'Batas bebas setahun, rupiah (orang pribadi)'], ['batasOmzet', 'Batas atas omzet setahun, rupiah']].map(([k, ket]) => h`<div data-k="pj-${k}"><div class="label">${ket}</div><input class="ketik-nama" type="text" inputmode="numeric" value="${d[k]}" data-ketik="pjProfilKetik" data-kunci="${k}"></div>`)}
        <div class="utama" data-aksi="pjProfilSimpan">SIMPAN PROFIL</div><div class="k2">${PJ.PJ_LABEL}.</div></div>`
      : h`<div class="kartu" data-k="pj-profil" style="gap: 2px;"><div class="label">1 · Profil wajib pajak</div>
        ${[['Atas nama', P.wpAtasNama || 'belum diisi'], ['Jenis', (PJ.PJ_JENIS_WP.find((j) => j.id === P.jenisWp) || {}).nama], ['Status PKP', (PJ.PJ_STATUS_PKP.find((j) => j.id === P.statusPkp) || {}).nama], ['Status pasangan', (PJ.PJ_STATUS_PASANGAN.find((j) => j.id === P.statusPasangan) || {}).nama], ['Tahun mulai tarif final', P.tahunMulaiTarifFinal === null ? 'tidak diketahui' : String(P.tahunMulaiTarifFinal)], ['Omzet tahun lalu', P.omzetTahunLalu === null ? 'tidak diketahui' : RP(P.omzetTahunLalu)],
          ['Tarif', P.tarifPerMil ? (P.tarifPerMil / 10).toFixed(1).replace('.', ',') + ' %' : 'belum diatur'], ['Batas bebas', P.batasBebas === null ? 'belum diisi' : RP(P.batasBebas)], ['Batas atas', P.batasOmzet ? RP(P.batasOmzet) : 'belum diatur']].map(([nm, v], i) => h`<div class="lp-terjun" data-k="pp-${i}"><span>${nm}</span><b>${v}</b></div>`)}
        ${T.anggapanOp ? h`<div class="pita-info emas" data-k="pj-anggapan">${PJ.PJ_ANGGAPAN_OP}</div>` : ''}${pasanganTeks(T.pasangan, 'pj-pasangan')}${P.jenisWp === 'badan' ? h`<div class="pita-info awas">Badan: kolom PPh tidak dihitung — tanyakan konsultan.</div>` : ''}
        <div class="k2">${P.sumberAturan ? 'Aturan: ' + P.sumberAturan.teks + ' · diisi ' + tanggalPendek(P.sumberAturan.tanggal) : 'Aturan belum diisi — tombol di bawah mengisinya; tiap angka tetap bisa lu ubah.'}</div>
        <div class="pj-dua"><div class="utama" data-aksi="pjPakaiAturan" data-k="pj-aturan">Pakai aturan PP 55/2022 jo. PP 20/2026</div><div class="kaca-btn" data-aksi="pjProfilBuka">ubah profil & angka</div></div></div>`;
    // 2 · tahun berjalan
    const skala = Math.max(1, ...T.daftar.map((b) => b.gabung));
    const bulan = h`<div class="kartu" data-k="pj-tahun" style="gap: 6px;"><div class="label">2 · Tahun ${T.tahun} · kumulatif ${T.kumTeks}</div>
      ${T.peringatanTahunLalu ? h`<div class="pita-info awas" data-k="pj-tahun-lalu">${T.peringatanTahunLalu}</div>` : ''}
      ${A.ada ? h`<div class="pj-ambang" data-k="pj-ambang"><div class="pj-rel"><span style="width: ${Math.min(100, A.pct).toFixed(1)}%;" class="${A.level >= 85 ? 'awas' : ''}"></span>${A.proyeksi ? h`<i class="proyeksi" style="left: ${Math.min(100, A.proyeksi.pct).toFixed(1)}%;" title="proyeksi akhir tahun [PERKIRAAN]"></i>` : ''}${PJ.PJ_AMBANG.map((x) => h`<em style="left: ${x}%;" class="${A.level >= x ? 'lewat' : ''}">${x}</em>`)}</div>
        <div class="k2">${A.teks}</div>${A.akibat ? h`<div class="pita-info awas">${A.akibat}</div>` : ''}</div>` : h`<div class="k2">Batas atas belum diatur — ambang Rp4,8 miliar tidak digambar.</div>`}
      <div class="pj-bulan" data-k="pj-bulan">${T.daftar.map((b) => h`<div class="pj-b ${b.status.awas ? 'awas' : ''} ${b.berjalan ? 'jalan' : ''}" data-k="pb-${b.key}">
        <div class="nm"><b>${b.pendek}</b><i style="height: ${Math.max(3, Math.round(b.gabung / skala * 40))}px;" class="${b.lengkap ? '' : 'kosong'}"></i></div>
        <div class="isi"><div>${b.lengkap ? RP(b.omzet) : '—'}${b.sistem !== null ? h` <small>sistem ${RP(b.sistem)}${b.sebagian ? ' (mulai ' + tanggalPendek(b.awalSistem) + ')' : ''}</small>` : h` <small>tidak ada di sistem</small>`}</div>
          ${b.lama !== null || b.lain !== null || b.pasangan !== null ? h`<div class="k2">${b.lama !== null ? diketik(b.lama, 'catatan lama') : ''} ${b.lain !== null ? diketik(b.lain, 'usaha lain') : ''} ${b.pasangan !== null ? diketik(b.pasangan, b.pasanganIkutPph ? 'usaha pasangan, ikut PPh' + (T.pasangan.anggapan ? ' (anggapan)' : '') : 'usaha pasangan, batas Rp4,8 miliar saja') : ''}</div>` : ''}
          <div class="k2">kumulatif ${RP(b.kum)}${b.pph !== null ? ' · PPh ' + RP(b.pph) : ''}${b.setor.length ? ' · disetor ' + RP(b.jumlahSetor) : ''}</div>
          ${b.potongan && b.potongan.jumlah ? h`<div class="k2" data-k="pb-pot-${b.key}">sebelum potongan nota ${RP(b.sebelumPotongan)} (potongan ${RP(b.potongan.jumlah)}) — angka kedua untuk konsultan</div>` : ''}</div>
        <div class="st"><span class="pj-status ${b.status.kode}">${b.status.teks}</span>${b.lengkap ? '' : h`<span class="tautan" data-aksi="pjLuarBuka" data-b="${b.key}" data-sumber="catatanLama">isi omzet</span>`}${b.pph > 0 && b.status.kode !== 'disetor' && !b.berjalan ? h`<span class="tautan" data-aksi="pjSetorBuka" data-b="${b.key}">catat setoran</span>` : ''}</div></div>`)}</div>
      <div class="k2">Jumlah perkiraan ${T.totalPph === null ? 'tidak dihitung' : RP(T.totalPph)} · setoran tercatat ${RP(T.totalSetor)} · setor s.d. tanggal ${P.tanggalLapor} bulan berikutnya, KAP-KJS 411128-420 lewat Coretax.</div>${label}</div>`;
    // 3 · setoran
    const ds = s.drafSetor; const semuaSetor = PJ.pjSetoranSemua().slice().reverse();
    const setoran = h`<div class="kartu" data-k="pj-setoran" style="gap: 6px;"><div class="label">3 · Setoran (bukti dari Coretax / bank) · ${semuaSetor.length}</div>
      ${ds ? h`<div class="pj-form" data-k="pj-setor-form"><div class="label">Masa pajak (bulan omzet yang disetori)</div><div class="lp-bulan">${T.daftar.slice().reverse().map((b) => h`<div class="seg ${ds.masaPajak === b.key ? 'aktif' : ''}" data-aksi="pjSetorKetikMasa" data-b="${b.key}">${b.pendek}</div>`)}</div>
        ${[['tanggalSetor', 'Tanggal setor', 'date'], ['jumlah', 'Jumlah disetor (rupiah)', 'text'], ['ntpn', 'NTPN (16 karakter angka/huruf di bukti setor)', 'text'], ['atasNama', 'Atas nama (nama saja)', 'text'], ['catatan', 'Catatan (wajib kalau dicatat mundur atau tanpa NTPN)', 'text']].map(([k, ket, tp]) => h`<div data-k="ps-${k}"><div class="label">${ket}</div><input class="ketik-nama" type="${tp}" ${k === 'jumlah' ? mentah('inputmode="numeric"') : ''} value="${ds[k]}" data-ketik="pjSetorKetik" data-kunci="${k}"></div>`)}
        ${ds.ntpn && PJ.pjCekNtpn(ds.ntpn) ? h`<div class="pita-info awas">${PJ.pjCekNtpn(ds.ntpn)}</div>` : ''}<div class="pj-dua"><div class="utama" data-aksi="pjSetorSimpan">CATAT SETORAN</div><div class="kaca-btn" data-aksi="pjSetorTutup">batal</div></div></div>`
        : h`<div class="kaca-btn aktif" data-aksi="pjSetorBuka" data-k="pj-setor-buka" style="min-height: 40px;">+ catat setoran</div>`}
      ${semuaSetor.map((x) => h`<div class="lp-baris dua" data-k="ps-${x.id}"><div><div>${LP.lpNamaBulan(x.masaPajak)} · ${RP(x.jumlah)}</div><div class="k2">disetor ${tanggalPendek(x.tanggalSetor)} · ${x.ntpn ? 'NTPN ' + x.ntpn : 'tanpa NTPN'}${x.catatan ? ' · ' + x.catatan : ''}${x.omzetSaatSetor !== null && x.omzetSaatSetor !== undefined ? ' · omzet saat dicatat ' + RP(x.omzetSaatSetor) : ''}</div></div>
        <div class="tautan ${s.yakinPj === 's:' + x.id ? 'awas-teks' : ''}" data-aksi="pjSetorHapus" data-id="${x.id}">${s.yakinPj === 's:' + x.id ? 'yakin hapus' : 'hapus'}</div></div>`)}
      <div class="k2">Setoran boleh untuk bulan yang belum tutup buku (kewajiban setor bulanan). Tanda "dilaporkan" di Bulanan tetap ada; untuk bulan yang punya setoran, statusnya diambil dari setoran.</div></div>`;
    // 4 · omzet di luar sistem
    const dl = s.drafLuar; const luar = PJ.pjOmzetLuarSemua().slice().sort((a, b) => String(b.id).localeCompare(String(a.id)));
    const kartuLuar = h`<div class="kartu" data-k="pj-luar" style="gap: 6px;"><div class="label">4 · Omzet di luar sistem · diketik owner</div>
      <div class="k2">Sistem ini mencatat sejak ${T.awalSistem ? tanggalPendek(T.awalSistem) : '—'}. Bulan sebelumnya (angka dari ayah), usaha lain wajib pajak yang sama, dan usaha pasangan diketik di sini — tampil beda dari hitungan sistem. Kosong ≠ nol.</div>
      ${dl ? h`<div class="pj-form" data-k="pj-luar-form"><div class="label">Sumber</div><div class="jalur rapat" style="flex-wrap: wrap;">${PJ.PJ_SUMBER_LUAR.map((x) => h`${pil(dl.sumber, x.id, 'pjLuarPilih', 'sumber')}${x.nama}</div>`)}</div><div class="k2">${dl.sumber === 'usahaPasangan' ? T.pasangan.teks : (PJ.PJ_SUMBER_LUAR.find((x) => x.id === dl.sumber) || {}).ket}</div>
        <div class="label">Bulan</div><input class="ketik-nama" type="month" value="${dl.bulan}" max="${bulanKini()}" data-ketik="pjLuarKetik" data-kunci="bulan">
        <div class="label">Jumlah (rupiah; ketik 0 kalau memang nol)</div><input class="ketik-nama" type="text" inputmode="numeric" value="${dl.jumlah}" data-ketik="pjLuarKetik" data-kunci="jumlah">
        <div class="label">Keterangan (dari mana angkanya)</div><input class="ketik-nama" type="text" value="${dl.keterangan}" data-ketik="pjLuarKetik" data-kunci="keterangan">
        <div class="pj-dua"><div class="utama" data-aksi="pjLuarSimpan">SIMPAN</div><div class="kaca-btn" data-aksi="pjLuarTutup">batal</div></div></div>`
        : h`<div class="kaca-btn aktif" data-aksi="pjLuarBuka" data-k="pj-luar-buka" style="min-height: 40px;">+ isi omzet di luar sistem</div>`}
      ${luar.map((x) => h`<div class="lp-baris dua" data-k="pl-${x.id}"><div><div>${LP.lpNamaBulan(x.bulan)} · ${diketik(x.jumlah, (PJ.PJ_SUMBER_LUAR.find((y) => y.id === x.sumber) || {}).nama || x.sumber)}</div>${x.keterangan ? h`<div class="k2">${x.keterangan}</div>` : ''}</div>
        <div class="tautan ${s.yakinPj === 'l:' + x.id ? 'awas-teks' : ''}" data-aksi="pjLuarHapus" data-id="${x.id}">${s.yakinPj === 'l:' + x.id ? 'yakin hapus' : 'hapus'}</div></div>`)}</div>`;
    const Dk = PJ.dokRekapPajak(T, LP.kopUntuk(LP.pakaiKop().pakai.omzet, LP.identitasUsaha())); if (!LP.identitasUsaha().lengkap) Dk.tolak = 'Kop belum lengkap';
    const cetak = h`${kertas(Dk, null, 'kertas-pajak')}${tigaTombol('pjKeluar', Dk.tolak)}`;
    const sumber = h`<div class="kartu platina" data-k="pj-sumber" style="gap: 2px;"><div class="label">Sumber aturan · dilihat 24 Sep 2026</div>${PJ.PJ_SUMBER.map((x, i) => h`<div class="k2" data-k="sa-${i}">${x.terverifikasi ? '' : h`<b class="awas-teks">[BELUM TERVERIFIKASI]</b> `}${x.klaim}</div>`)}</div>`;
    if (L === 'hp') return h`<section data-k="pajak">${label}${bulan}${profil}${setoran}${kartuLuar}${cetak}${sumber}</section>`;
    return h`<section data-k="pajak">${label}${grid(L, [h`${bulan}`, h`${profil}${kartuLuar}`, h`${setoran}${cetak}${sumber}`])}</section>`;
  }

  // ---------- NERACA
  function gambarNeraca(s, L) {
    const sampai = s.sampaiN || null; const NP = LP.neracaPada(sampai, kini()); const BD = LP.bandingKekayaan(kini()); const arah = (n) => (n < 0 ? 'rugi' : '');
    const hero = h`<div class="kartu hero" data-k="hero" style="gap: 4px;"><div class="label">Kekayaan toko ${sampai ? 'per ' + tanggalPendek(sampai) : 'hari ini'} · kalau semuanya dihitung</div><div class="lp-besar ${NP.total === null ? 'kosong' : arah(NP.total)}" ${NP.total === null ? '' : mentah('data-gulir="' + Math.round(NP.total) + '"')}>${NP.total === null ? 'belum bisa dihitung' : RP(NP.total)}</div>
      <div class="k2">${NP.total === null ? 'Kas belum bisa dihitung (titik kas belum disetel) — Tutup hari malam ini menyetelnya.' : 'Harta ' + RP(NP.aset) + ' − kewajiban ' + RP(NP.kewajiban) + '. ' + BD.teks}</div>
      <div style="display: flex; gap: 6px; flex-wrap: wrap; align-items: center;"><input class="ketik-nama" type="date" value="${s.sampaiN}" max="${iso()}" data-ketik="nrSampai" style="max-width: 170px; min-height: 36px;">${s.sampaiN ? h`<div class="kaca-btn kecil" data-aksi="nrHariIni">hari ini</div>` : h`<span class="k2">pilih tanggal untuk melihat neraca hari lain</span>`}</div></div>`;
    const dua = h`<div class="kartu" data-k="dua" style="gap: 8px;"><div class="lp-dua-sisi"><div><div class="label">Harta</div>${NP.harta.map((r, i) => h`<div class="lp-terjun" data-k="ha-${i}"><span>${r.nama}${r.ket ? h`<small> · ${r.ket}</small>` : ''}</span><b class="${arah(r.n)}">${r.n === null ? '—' : RP(r.n)}</b></div>`)}<div class="lp-terjun jumlah"><span>Jumlah harta</span><b>${NP.aset === null ? '—' : RP(NP.aset)}</b></div></div>
      <div><div class="label">Kewajiban & modal</div>${NP.pasiva.map((r, i) => h`<div class="lp-terjun" data-k="pa-${i}"><span>${r.nama}</span><b class="${arah(r.n)}">${r.n === null ? '—' : RP(r.n)}</b></div>`)}<div class="lp-terjun jumlah"><span>Jumlah</span><b>${NP.aset === null ? '—' : RP(NP.kewajiban + NP.modal + NP.labaDitahan)}</b></div></div></div>
      <div class="lp-seimbang ${NP.tolak ? 'awas' : ''}">${NP.tolak || NP.catatan}</div>${NP.N.adaStokMinus ? h`<div class="kaca-btn kecil" data-aksi="tujuan" data-ke="stok" data-lembar="cocok" style="align-self: flex-start;">cocokkan stok di Stok ›</div>` : ''}</div>`;
    const D = LP.laporanBerkop('neraca', (sampai || iso()).slice(0, 7), 1, kini()); if (sampai) { D.sub = 'per ' + tanggalPendek(sampai) + ' · ' + (D.final ? 'FINAL' : 'DRAF — belum tutup buku'); D.baris = barisNeraca(NP); D.catatan = NP.catatan; D.tolak = NP.tolak || D.tolak; }
    const kertasN = h`${kertas(D, null, 'kertas-neraca')}${tigaTombol('nrKeluar', D.tolak)}`;
    const atur = s.aturN ? h`<div class="kartu lp-lembar" data-k="aturN" style="gap: 8px;"><div class="kepala-lembar"><div class="serif" style="font-size: 18px;">Aset tetap</div><div class="kaca-btn" data-aksi="nrAturTutup">tutup</div></div><div class="label">Nilai timbangan, mesin jahit, kendaraan dsb. (rupiah) — isian owner sampai modul aset tetap ada</div><input class="ketik-nama" type="text" inputmode="numeric" value="${s.aturN.asetTetap}" data-ketik="nrAturKetik" data-kunci="asetTetap"><div class="label">Keterangan</div><input class="ketik-nama" type="text" value="${s.aturN.asetKet}" data-ketik="nrAturKetik" data-kunci="asetKet" placeholder="mis. timbangan digital, mesin jahit karung"><div class="utama" data-aksi="nrAturSimpan">SIMPAN</div></div>`
      : h`<div class="kaca-btn" data-aksi="nrAturBuka" data-k="aturN-buka" style="min-height: 38px; font-size: 12px;">Atur aset tetap · ${NP.asetTetap ? RP(NP.asetTetap) : 'belum diisi (tidak ikut dihitung)'}</div>`;
    const kaki = h`<div class="lp-kaki">Stok dinilai dengan HPP (modal), bukan harga jual — sengaja konservatif. Stok minus MENGURANGI kekayaan, tidak dinilai nol. Laba ditahan dihitung sebagai sisa; pembandingnya laba kumulatif mesin, bedanya disebut, tidak disembunyikan. Batas BAWAH: aset tetap hanya isian owner.</div>`;
    if (L === 'hp') return h`<section data-k="neraca">${hero}${dua}${atur}${kertasN}${kaki}</section>`;
    return h`<section data-k="neraca">${grid(L, [h`${hero}${atur}${kaki}`, h`${dua}`, h`${kertasN}`])}</section>`;
  }

  // ---------- DOKUMEN · DK2 + DK4
  function gambarDokumen(s, L) {
    const daftar = LP.daftarBulan(kini(), 12); const ke = s.keD && daftar.some((b) => b.key === s.keD) ? s.keD : bulanKini();
    const tab = h`<div class="jalur rapat" data-k="tabD">${[['laporan', 'Laporan berkop'], ['paket', 'Paket bank'], ['banding', 'Banding'], ['kecil', 'Dokumen kecil']].map(([id, nm]) => h`<div class="seg ${s.tabD === id ? 'aktif' : ''}" data-aksi="dkTab" data-t="${id}" data-k="td-${id}">${nm}</div>`)}</div>`;
    let kiri, tengah, kanan;
    if (s.tabD === 'laporan' || s.tabD === 'banding') {
      const pilih = h`<div class="kartu" data-k="pilihD" style="gap: 8px;">${s.tabD === 'laporan' ? h`<div class="lp-tab3">${LP.JENIS_LAPORAN.map(([id, nm]) => h`<div class="seg ${s.jenisD === id ? 'aktif' : ''}" data-aksi="dkJenis" data-j="${id}" data-k="jd-${id}">${nm}</div>`)}</div>` : ''}<div class="label">Bulan akhir · ✎ = belum tutup buku (DRAF)</div>${bulanCip('dkKe', ke, daftar)}
        ${s.tabD === 'laporan' ? h`<div class="lp-deret">${LP.RENTANG_LAPORAN.map(([n, nm]) => h`<div class="seg ${s.rentangD === n ? 'aktif' : ''}" data-aksi="dkRentang" data-n="${n}" data-k="rt-${n}">${nm}</div>`)}</div>` : h`<div class="label">banding dengan</div>${bulanCip('dkBanding', s.bandingD || (daftar[1] || daftar[0]).key, daftar)}`}</div>`;
      if (s.tabD === 'laporan') { const D = LP.laporanBerkop(s.jenisD, ke, s.rentangD, kini()); kiri = pilih; tengah = h`${kertas(D, null, 'kertas-' + D.jenis)}${tigaTombol('dkKeluar', D.tolak)}`; }
      else { const b = s.bandingD || (daftar[1] || daftar[0]).key; const BD = LP.bandingLabaRugi(ke, b, kini()); const kop = LP.kopUntuk('penuh'); kiri = pilih; tengah = h`<div class="dk-kertas" data-k="kertas-banding">${kopHtml(kop)}<div class="dk-judul">Banding Laba-Rugi</div><div class="dk-sub">${BD.judul}</div><table class="dk-tabel lp-banding">${BD.baris.map((r, i) => h`<tr data-k="bd-${i}"><td>${r.nama}</td><td class="n">${RP(r.a)}</td><td class="n">${RP(r.b)}</td><td class="d ${r.arah}">${r.teksD}</td></tr>`)}</table><div class="dk-kaki"><span>kolom: bulan terpilih · pembanding · selisih</span><span>kop v${kop.versi}</span></div></div>`; }
      kanan = riwayatHtml();
    } else if (s.tabD === 'paket') {
      const P = LP.paketBank(s.paket, kini());
      kiri = h`<div class="kartu" data-k="paket" style="gap: 4px;"><div class="label">Paket untuk bank</div>${P.isi.map((p) => h`<div class="lp-cek" data-aksi="dkPaket" data-id="${p.id}" data-k="pk-${p.id}"><span class="kotak ${p.dipilih ? 'isi' : ''}">${p.dipilih ? '✓' : ''}</span><span>${p.nama}</span></div>`)}<div class="k2">${P.ket}</div><div class="${P.tolak ? 'utama redup' : 'utama'}" data-aksi="dkPaketSusun" style="min-height: 44px; font-size: 13px;">${P.tolak || 'SUSUN PAKET BANK · ' + P.nPilih + ' dokumen'}</div></div>`;
      tengah = P.daftar.length ? h`${P.daftar.slice(0, 2).map((D, i) => kertas(D.jenis === 'omzet' ? dokRekap() : D, null, 'pk-kertas-' + i))}` : h`<div class="kartu" data-k="paket-kosong"><div class="ket">Paket bank hanya dari bulan yang sudah tutup buku. Sampai tutup buku pertama (Uang → Tutup buku), cetak laporan biasa — ia bercap DRAF dan tetap bisa dipakai untuk membaca keadaan toko.</div></div>`;
      kanan = riwayatHtml();
    } else {
      const D = LP.dokumenKecil(s.jenisK, s.pilihK[s.jenisK] || null, s.cariK, kini());
      kiri = h`<div class="lp-rak" data-k="rak">${LP.JENIS_KECIL.map((j) => h`<div class="lp-ubin ${s.jenisK === j.id ? 'aktif' : ''}" data-aksi="dkKecilJenis" data-j="${j.id}" data-k="ub-${j.id}"><b>${j.nama}</b><span class="k2">${j.ket}</span></div>`)}</div>
        ${s.jenisK === 'nota' ? h`<div class="kartu" data-k="cari" style="gap: 6px;"><div class="label">Cari nota (nama pembeli atau isinya) · 60 hari terakhir</div><input class="ketik-nama" type="text" value="${s.cariK}" data-ketik="dkKecilCari" placeholder="mis. Angsa, nama pembeli"><div class="k2">${D.cocokN} nota cocok · nota dibatalkan tidak bisa dicetak ulang</div></div>` : ''}
        ${D.pilihan.length ? h`<div class="kartu" data-k="pilihan-${s.jenisK}" style="padding: 6px 8px; gap: 0;">${D.pilihan.slice(0, 40).map((p) => h`<div class="lp-pilih ${(s.pilihK[s.jenisK] || D.pilihan[0].id) === p.id && (s.jenisK !== 'nota' || s.pilihK.nota) ? 'aktif' : ''}" data-aksi="dkKecilPilih" data-id="${p.id}" data-k="pl-${p.id}"><span>${p.nama}</span><span class="n">${p.ket ? p.ket + ' ' : ''}${RP(p.n)}</span></div>`)}</div>` : ''}`;
      tengah = h`${kertas(D, null, 'kertas-kecil-' + D.jenis)}${tigaTombol('dkKecilKeluar', D.tolak)}`; kanan = riwayatHtml();
    }
    const kaki = h`<div class="lp-kaki">Satu halaman per laporan, berkop. Bulan ✎ belum tutup buku → cap DRAF. Neraca yang kasnya belum bisa dihitung atau stoknya minus tidak dicetak; kas akhir arus kas = kas neraca. "Simpan PDF" = dialog cetak perangkat → Simpan sebagai PDF. Dokumen kecil: angkanya dari catatan modul lain, di sini cuma disusun, diberi kop, dinomori.</div>`;
    if (L === 'hp') return h`<section data-k="dokumen">${tab}${kiri}${tengah}${kanan}${kaki}</section>`;
    return h`<section data-k="dokumen">${tab}${grid(L, [h`${kiri}${kaki}`, h`${tengah}`, h`${kanan}`])}</section>`;
  }

  // ---------- SETELAN · DK1
  function gambarSetelan(s, L) {
    const I = LP.identitasUsaha(); const d = s.drafI || I; const P = LP.pakaiKop(); const berubah = !!s.drafI && (LP.KOLOM_IDENTITAS.some((k) => (d[k.id] || '') !== (I[k.id] || '')) || d.gaya !== I.gaya || !!d.npwpDiKop !== !!I.npwpDiKop); const awasNpwp = LP.peringatanNpwp(d.npwp); const tolak = berubah ? LP.periksaIdentitas(d) : ''; const K1 = LP.KOLOM_IDENTITAS.find((k) => k.id === s.isiI) || null;
    const kartuId = h`<div class="kartu" data-k="identitas" style="gap: 6px;"><div class="label">Kop & identitas usaha · ${I.versi ? 'kop v' + I.versi : 'kop bawaan — belum pernah disimpan'}${I.dariStruk ? ' · alamat & telepon dari setelan struk' : ''}</div>
      <div class="lp-id" data-k="kolom">${LP.KOLOM_IDENTITAS.map((k) => h`<div class="${s.isiI === k.id ? 'aktif' : ''}" data-aksi="stIsi" data-kol="${k.id}" data-k="kol-${k.id}"><span class="k">${k.nama}</span><span class="${String(d[k.id] || '').trim() ? '' : 'kosong'}">${String(d[k.id] || '').trim() || (k.ket === 'wajib' ? '(wajib — belum diisi)' : '(belum ada)')}</span></div>`)}</div>
      ${K1 ? h`<div data-k="isi-${K1.id}" style="display: flex; flex-direction: column; gap: 6px;"><div class="label">${K1.nama} · ${K1.ket}</div><input class="ketik-nama" type="text" value="${d[K1.id] || ''}" data-ketik="stKetik" placeholder="ketik di sini" autofocus></div>` : h`<div class="k2">Ketuk baris untuk mengisi. Nama & alamat wajib; NPWP/NIB boleh kosong sampai ada — barisnya tidak dicetak.</div>`}
      <div class="lp-deret">${[['kiri', 'Kop di kiri'], ['tengah', 'Kop di tengah']].map(([g, nm]) => h`<div class="seg ${d.gaya === g ? 'aktif' : ''}" data-aksi="stGaya" data-g="${g}" data-k="gy-${g}">${nm}</div>`)}</div>
      ${String(d.npwp || '').trim() ? h`<div class="label">NPWP di kop (bawaan: tidak dicetak di kop mana pun)</div><div class="lp-deret" data-k="npwp-kop">${[['tidak', 'Tidak dicetak'], ['ya', 'Cetak di kop penuh']].map(([v, nm]) => h`<div class="seg ${(d.npwpDiKop === true) === (v === 'ya') ? 'aktif' : ''}" data-aksi="stNpwpKop" data-v="${v}" data-k="nk-${v}">${nm}</div>`)}</div>` : ''}
      ${awasNpwp ? h`<div class="pita-info awas" data-k="awas-npwp">${awasNpwp}${d.npwpDiKop === true ? ' Sekarang disetel DICETAK di kop penuh.' : ''}</div>` : ''}
      ${tolak ? h`<div class="pita-info awas" data-k="tolak-id">${tolak}</div>` : ''}<div class="lp-tiga"><div class="kaca-btn kecil" data-aksi="stKosongkan">kosongkan</div><div class="kaca-btn kecil" data-aksi="stBatal">buang perubahan</div><div class="utama ${berubah && !tolak ? '' : 'redup'}" data-aksi="stSimpan" style="min-height: 36px; font-size: 12px;">${!berubah ? 'tidak ada perubahan' : tolak ? 'periksa dulu' : 'SIMPAN → kop v' + (I.versi + 1)}</div></div></div>`;
    const kp = (ragam) => LP.kopUntuk(ragam, Object.assign({}, I, d));
    const pratinjau = h`<div class="kartu" data-k="pratinjau" style="gap: 6px;"><div class="label">Pratinjau${berubah ? ' · perubahan belum disimpan' : ''}</div><div class="k2">Kop penuh — laporan, bank, pajak</div><div class="dk-kertas" data-k="pp"><div class="dk-kop ${d.gaya === 'tengah' ? 'tengah' : ''}"><div><div class="nm">${kp('penuh').nama}</div><div class="al">${kp('penuh').alamat || '(alamat)'}</div><div class="al">${kp('penuh').resmi || (String(d.npwp || '').trim() ? 'NPWP tidak dicetak (bawaan)' + (d.nib ? '' : '; NIB belum ada') : 'NPWP/NIB belum ada — baris ini tidak dicetak')}</div></div></div><div class="dk-judul">Laporan Laba-Rugi</div><div class="dk-sub">contoh tata letak</div><div class="dk-kaki"><span>${d.slogan || ''}</span><span>kop v${I.versi + (berubah ? 1 : 0)}</span></div></div>
      <div class="k2">Kop ringkas — nota & kartu pelanggan</div><div class="dk-kertas" data-k="pr"><div class="dk-kop ${d.gaya === 'tengah' ? 'tengah' : ''}"><div><div class="nm">${kp('ringkas').nama}</div><div class="al">${kp('ringkas').alamat || '(alamat)'}</div></div></div><div class="dk-judul">Nota</div><div class="dk-sub">contoh tata letak</div><div class="dk-kaki"><span>${d.slogan || ''}</span><span>Terima kasih</span></div></div></div>`;
    const pakai = h`<div class="kartu" data-k="pakai" style="gap: 2px;"><div class="label">Dokumen mana memakai kop mana · ketuk untuk menukar</div>${LP.DOKUMEN_KOP.map((x) => h`<div class="lp-pilih" data-aksi="stPutar" data-d="${x.id}" data-k="pk-${x.id}"><span>${x.nama}</span><span class="lp-cip ${P.pakai[x.id] === 'penuh' ? 'emas' : 'ok'}">${P.pakai[x.id] === 'penuh' ? 'kop penuh' : 'kop ringkas'}</span></div>`)}<div class="k2" style="padding-top: 6px;">Kop ringkas = tanpa NPWP/NIB (untuk pelanggan); kop penuh = untuk bank & pajak, dengan NIB — NPWP hanya kalau lu menyalakannya.${!I.nib && !(I.npwp && I.npwpDiKop) ? ' Saat ini kop penuh sama dengan ringkas.' : ''}</div></div>`;
    const nomor = s.aturD ? h`<div class="kartu lp-lembar" data-k="aturD" style="gap: 8px;"><div class="kepala-lembar"><div class="serif" style="font-size: 18px;">Nomor dokumen</div><div class="kaca-btn" data-aksi="stAturTutup">tutup</div></div><div class="label">Nomor urut dokumen berikutnya dimulai dari (kalau melanjutkan buku lama) · terakhir terpakai No. ${ANGKA(LP.nomorTerakhir())}</div><input class="ketik-nama" type="text" inputmode="numeric" value="${s.aturD.nomorAwal}" data-ketik="stAturKetik"><div class="utama" data-aksi="stAturSimpan">SIMPAN</div></div>`
      : h`<div class="kaca-btn" data-aksi="stAturBuka" data-k="aturD-buka" style="min-height: 38px; font-size: 12px;">Nomor dokumen berikutnya · No. ${ANGKA(LP.nomorBerikut())}</div>`;
    const riwayat = I.riwayat.length ? h`<div class="kartu platina" data-k="riwayat-kop" style="gap: 2px;"><div class="label">Riwayat kop</div>${I.riwayat.slice(0, 10).map((r) => h`<div class="lp-baris dua" data-k="rk-${r.versi}"><div><div>Kop v${r.versi}: ${(r.ubah || []).join(', ')} diubah</div><div class="k2">${tanggalPendek(r.tanggal)} ${r.jam || ''}</div></div></div>`)}</div>` : '';
    const lain = h`<div class="kartu" data-k="atur-lain" style="gap: 2px;"><div class="label">Setelan lain — tinggal di layarnya masing-masing</div>${LP.ATUR_LAIN.map((a, i) => h`<div class="lp-pilih" data-aksi="tujuan" data-ke="${a.tujuan.ke}" data-keluarga="${a.tujuan.keluarga || ''}" data-tab="${a.tujuan.tab || ''}" data-lembar="${a.tujuan.lembar || ''}" data-sistem="${a.tujuan.sistem || ''}" data-k="al-${i}"><span><div>${a.nama}</div><div class="k2">${a.ket}</div></span><span class="k2">›</span></div>`)}
      <div class="k2" style="padding-top: 6px;">Nama perangkat, jejak pencatat, cadangan & kuota ada di Menu → Toko ini. Memulihkan dari berkas cadangan tetap lewat sistem lama (keputusan owner). Tidak ada kolom PIN/sandi di sistem baru — kunci perangkat diatur di perangkatnya.</div></div>`;
    const kaki = h`<div class="lp-kaki">Tiap simpan identitas = versi kop baru; dokumen yang sudah dicetak tetap menyebut versi lamanya. Kop ringkas ikut ke nota di Jual (satu kop, dua ragam). Alamat/NPWP/NIB = isian owner, bukan data toko.</div>`;
    if (L === 'hp') return h`<section data-k="setelan">${kartuId}${pratinjau}${pakai}${nomor}${riwayat}${lain}${kaki}</section>`;
    return h`<section data-k="setelan">${grid(L, [h`${kartuId}${nomor}${riwayat}${kaki}`, h`${pratinjau}${pakai}`, h`${lain}`])}</section>`;
  }

  K.dengar(gambar); dengarkan(() => gambar());
  let tundaUkur = null; window.addEventListener('resize', () => { clearTimeout(tundaUkur); tundaUkur = setTimeout(gambar, 160); });
  const buka = (keluarga, t) => { AKSI.keluarga({ nama: LP.KELUARGA_LAPORAN.some((k) => k[0] === keluarga) ? keluarga : 'laba' }); if (t && t.awal && keluarga === 'mingguan') set({ mingguM: t.awal }); if (t && t.tahun && keluarga === 'tahunan') set({ tahunT: Number(t.tahun) }); if (t && t.tab && keluarga === 'dokumen') set({ tabD: t.tab }); if (t && t.jenis && keluarga === 'dokumen') set({ tabD: 'kecil', jenisK: t.jenis }); if (t && t.bulan && keluarga === 'laba') set({ bulanL: t.bulan }); };
  return { gambar, buka, tampilkan: (ya) => { const tadi = tampil; tampil = !!ya; if (tampil && !tadi) { akar.classList.remove('masuk'); void akar.offsetWidth; akar.classList.add('masuk'); setTimeout(() => akar.classList.remove('masuk'), 1200); } if (tampil) gambar(); } };
}
